### ISSUE TITLE
clickhouse query format bug

### ISSUE THREAD

**Issue by dannielwallace** [childe/gohangout#10]
NewClickhouseOutput
fields[i] = fmt.Sprintf(`"%s"`, p.fields[i])
需要修改成:
fields[i] = fmt.Sprintf(`%s`, p.fields[i])

**Comment by dannielwallace** [comment]
另外：
根目录下的两个config相关的代码文件建议移到一个新的config目录下

**Comment by childe** [comment]
加双引号会出错吗? 我们这里跑了一段时间了好像也没问题.
