### ISSUE TITLE
请问elasticsearch支持https嘛？

### ISSUE THREAD

**Issue by queerkid** [childe/gohangout#100]
我的es集群设置成https访问了，gohangout一直在报错
failed to send heartbeat, restart: The group is rebalancing, so a rejoin is needed.
E0831 18:10:44.333046   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:10:44.504546   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:10:44.668342   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:10:56.237077   20779 group_consumer.go:455] failed to send heartbeat, restart: The group is rebalancing, so a rejoin is needed.
E0831 18:11:14.834871   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:11:15.016763   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:11:15.193485   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:11:45.361101   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:11:45.469786   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:11:45.634336   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:12:15.802169   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:12:15.992376   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk
E0831 18:12:16.166942   20779 bulk_http.go:164] bulk failed with https://elastic:********@10.10.41.165:9200/_bulk

**Comment by childe** [comment]
抱歉忘了回了...

运行的时候加一个参数  `-v 5`, 可以看到详细的报错信息, 包括response.

**Comment by queerkid** [comment]
> 抱歉忘了回了...
> 
> 运行的时候加一个参数 `-v 5`, 可以看到详细的报错信息, 包括response.

没关系，我已经放弃使用https了。哈哈
