### ISSUE TITLE
从kafka中读取数据写入至ES丢失数据

### ISSUE THREAD

**Issue by vipsql** [childe/gohangout#102]
现象:
   1.Kafka有在正常的消费
   2.处理程序无任何错误日志
   3.ES中没有接受到数据

处理函数: 时间戳转换

同样的数据   处理方式,采用filebeats没有此问题

**Comment by huangjacky** [comment]
需要一些更详细的信息，以及gohangout的日志

**Comment by saosir** [comment]
> 现象: 1.Kafka有在正常的消费 2.处理程序无任何错误日志 3.ES中没有接受到数据
> 
> 处理函数: 时间戳转换
> 
> 同样的数据 处理方式,采用filebeats没有此问题

同丢数据，量级挺大，无任何报错

**Comment by childe** [comment]
> 

没这么问问题的。
