### ISSUE TITLE
kafka output如何配置用户密码，和input类似

### ISSUE THREAD

**Issue by bj1116** [childe/gohangout#109]
kafka output如何配置用户密码，和input类似，另外output lz4编码有问题

**Comment by childe** [comment]
1. 看了一下, output 里面还没有写好, 我去修改一下

2. Lz4的问题暂时解决不了, 需要大改一下, 实现 Kafak 比较新的协议的, 整个框架也都要改.

最近看到有新的 Kafka 框架出来, 也可以考虑使用别的 Kafka 框架, 我有空了也写一个别的 Kafka 库的 Plugin.

**Comment by childe** [comment]
@bj1116  v1.5.0 版本添加了这个配置, 但我现在不搞这个东西, 也没有环境测试了.. :(

**Comment by bj1116** [comment]
好的，谢谢，可以使用sarama的库，还比较稳定，咱们那个input的库如果kafka重启，重连有问题

**Comment by bj1116** [comment]
这样增加用户密码好像不行，报错
E1022 11:45:18.328706   22900 producer.go:39] init brokers error: could not get any available broker from 192.168.100.17:9092
F1022 11:45:18.331698   22900 kafka_output.go:60] could not create kafka producer

**Comment by childe** [comment]
嗯嗯, 现在工作也不做这块了, 没有精力去更新 Kafka 的库.  Sarama 现在也支持了 Group Consumer, 建议使用这个吧~
