### ISSUE TITLE
govendor sync  报错

### ISSUE THREAD

**Issue by taojicai** [childe/gohangout#11]
git reset --hard cdf5f9a3308af3e7c53631ff7f2f42998cfc84fa
fatal: Could not parse object 'cdf5f9a3308af3e7c53631ff7f2f42998cfc84fa'.
Error: Remotes failed for:
        Failed for "github.com/childe/healer" (failed to sync repo to cdf5f9a3308af3e7c53631ff7f2f42998cfc84fa): exit status 128

**Comment by childe** [comment]
抱歉, 忘了把 github.com/childe/healer 最新commit push上来了.  已经push
