### ISSUE TITLE
数据的时间本身就是北京时间，为什么写到ch的时间多了8个小时

### ISSUE THREAD

**Issue by HendSame** [childe/gohangout#110]
![image](https://user-images.githubusercontent.com/9264192/97077699-5c63c280-1618-11eb-8e32-2b0c96e3bd78.png)

当前时间：2020-10-24 16：38:00

![image](https://user-images.githubusercontent.com/9264192/97077691-4e15a680-1618-11eb-9455-9395662288b5.png)

![image](https://user-images.githubusercontent.com/9264192/97077671-28889d00-1618-11eb-8ba0-43729607a204.png)

**Comment by childe** [comment]
给数据和具体现象

**Comment by childe** [comment]
给具体数据和现象



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HendSame <notifications@github.com&gt;
发送时间: 2020年10月24日 11:54
收件人: childe/gohangout <gohangout@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[childe/gohangout] 数据的时间本身就是北京时间，为什么写到ch的时间多了8个小时 (#110)
