### ISSUE TITLE
sasl authenticate error : EOF

### ISSUE THREAD

**Issue by kim-up** [childe/gohangout#111]
![image](https://user-images.githubusercontent.com/9264192/97085443-24787180-1650-11eb-8aa1-af3e86c57dad.png)
inputs:
    - Kafka: 
        decorate_events: false
        topic: 
            topicname: 5
        #assign:
        #   weblog: [0,9]
        codec: plain
        consumer_settings: 
            bootstrap.servers: "xxxxxx:9093"
            group.id: xxxxxx
            max.partition.fetch.bytes: '10485760'
            auto.commit.interval.ms: '5000'
            from.beginning: 'false'
            sasl.mechanism: 'PLAIN'
            sasl.user: '******'
            sasl.password: '*******'

首先我确定username和password 是有效的SASL_SS配置的用户名和密码。

是不是哪里配置的不对

Kafka version ：1.1.0
gohangout version:1.4.9

**Comment by bj1116** [comment]
确定sasl-plain，应该没啥问题

**Comment by childe** [comment]
把日志发来看一下吧. 
gohangout -v 5 --logtostderr 会把日志打印到屏幕上.

另外, 看一下 Kafka Server 日志, 看一下服务端有啥报错信息.

现在使用的自己写的 Kafka 的库, 没精力去更新维护了. 可以试一下 Sarama  库~

**Comment by hhalei** [comment]
这个问题最后怎么解决的，我这边也遇到了

**Comment by childe** [comment]
> 这个问题最后怎么解决的，我这边也遇到了

不知道，一直没有日志给我，就关掉了。发一下具体的应用的日志吧。

**Comment by hhalei** [comment]
服务端不在我们这边，是另一个部门维护的kafka

**Comment by childe** [comment]
> 服务端不在我们这边，是另一个部门维护的kafka

Gohangout 的日志发一下看看

**Comment by hhalei** [comment]
E0421 18:47:46.871753   19422 broker.go:63] sasl authenticate error : EOF
I0421 18:47:46.871828   19422 brokers.go:35] init broker from host1:9110 error:EOF
E0421 18:47:46.876881   19422 broker.go:63] sasl authenticate error : EOF
I0421 18:47:46.876942   19422 brokers.go:35] init broker from host2:9110 error:EOF
E0421 18:47:46.881116   19422 broker.go:63] sasl authenticate error : EOF
I0421 18:47:46.881179   19422 brokers.go:35] init broker from host3:9110 error:EOF
F0421 18:47:46.881255   19422 kafka_input.go:104] could not init GroupConsumer: could not get any available broker from host1:9110,host2:9110,host3:9110

**Comment by hhalei** [comment]
> > 服务端不在我们这边，是另一个部门维护的kafka
> 
> Gohangout 的日志发一下看看

用户名密码，都是没问题的，用java版本的hangout可以正常消费，
怀疑会不会跟kafka版本有关.

**Comment by childe** [comment]
@hhalei 麻烦再发一下，你是哪一个版本的 Gohangout？

**Comment by hhalei** [comment]
> @hhalei 麻烦再发一下，你是哪一个版本的 Gohangout？

v1.8.1

**Comment by childe** [comment]
看了一下代码，身份验证这里有两次请求，第一次是“握手”，接下来做一次“用户密码的验证”。不确定是哪时EOF了，还是要看一下Kafka 服务的日志。。:(

**Comment by childe** [comment]
可能是kafka版本的问题，我是使用的比较早的协议。可能新版的Kafka已经不再兼容这套认证方式了。

**Comment by childe** [comment]
fixed in https://github.com/childe/healer/commit/5b3784b892ff69acf364c2af34f2221a66a95c20
