### ISSUE TITLE
是否支持在导入过程中查询第三张表？

### ISSUE THREAD

**Issue by Lijiaqi1992** [childe/gohangout#112]
input:kafka
output:clickhouse
想在kafka消费导入过程中查询clickhouse中一个表的数据得到几个字段，再存入clickhouse中。
比如从kafka可以获取到手机号，用手机号查询某个表（与output同库）得到用户名和性别2个字段， 然后将其存入output指定表中。
不知道这个情况是否支持？

**Comment by childe** [comment]
现在不支持.

**Comment by childe** [comment]
如果总的数据量不是很大, 可以使用 Translate . 

先把数据映射都拉出来, 然后使用  Translate 插件翻译. 插件中可以配置更新的时长, 热更新.

**Comment by Lijiaqi1992** [comment]
> 如果总的数据量不是很大, 可以使用 Translate .
> 
> 先把数据映射都拉出来, 然后使用 Translate 插件翻译. 插件中可以配置更新的时长, 热更新.
数据量比较大，约1.7亿。Translate 说明中的地址访问不到，格式是什么样的？
还有如果Translate 可以使用的话，我需要查询的是多个字段，字段的连接和分割都是可配置的吗？
