### ISSUE TITLE
每天两千亿条数据用了多少台什么配置的机器能给出下么?

### ISSUE THREAD

**Issue by zcc1234567** [childe/gohangout#12]

**Comment by childe** [comment]
跑在k8s平台的, 只能大概估一下, 在1600个核左右吧.

**Comment by zcc1234567** [comment]
还有就是那么高的tps，es的数据写入能撑得住么，是不是存储做了优化。
另外没有考虑过使用flink，spark，jstorm等一些分布式数据处理系统

**Comment by zcc1234567** [comment]
使用jstorm，支持自定义正则切割，json解析，join以及完全自定义的代码解析。从语言上来说，Go比Java等语言资源消耗要小的多，而且轻量。分布式处理例如storm这种，使用拓扑，好处也显而易见。无状态数据处理:比如一种类型的数据需要经过spout以及多个bolt的处理，但不同bolt的的操作不同，耗时也不同，可以通过配置不同bolt的并发线程数来使整个解析，格式化过程不受木桶理论约束，流的合并和拆分在一些场景下也非常有用。对于有状态数据:可以通过路由规则路由到某个或者某组线程。
