### ISSUE TITLE
往clickhouse里写数据不能支持Int?

### ISSUE THREAD

**Issue by libiao163** [childe/gohangout#121]
kafka里的json串：
{"@timestamp":"2021-02-23T03:35:28.485Z","@metadata":{"beat":"filebeat","type":"_doc","version":"7.11.1"},"upstream_addr":"","request_uri":"/","upstream_response_time":"0","server_name":"localhost","upstream_status":"","nginx_version":"1.18.0","http_x_forwarded_for":"","http_referer":"","http_x_status":"","@version":1,"http_remoteip":"","remote_addr":"172.16.XX.XX","status":304,"request_method":"GET","msec":"1614051325.065","server_addr":"10.XX.XX.XX","pid":124996,"body_bytes_sent":0,"http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36","http_guid":"","scheme":"http","upstream_header_time":"","server_port":80,"connection_requests":2,"request_id":"e37f3ccbddbd6189c33df9b894977c05","request_time":0,"server_protocol":"HTTP/1.1"}

往clickhouse里写入报错：
E0223 03:34:56.244788  125623 clickhouse_output.go:347] exec clickhouse insert map[@metadata:map[beat:filebeat type:_doc version:7.11.1] @timestamp:2021-02-23T03:34:53.483Z @version:1 body_bytes_sent:0 connection_requests:1 http_guid: http_referer: http_remoteip: http_user_agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 http_x_forwarded_for: http_x_status: msec:1614051286.647 nginx_version:1.18.0 pid:124996 remote_addr:172.16.XX.XX request_id:e42ade5e91a3344a4957af399907e4d6 request_method:GET request_time:0 request_uri:/ scheme:http server_addr:10.XX.XX.XX server_name:localhost server_port:80 server_protocol:HTTP/1.1 status:304 upstream_addr: upstream_header_time: upstream_response_time:0 upstream_status:] error: status (Int8): unexpected type string

麻烦帮忙看一下，3X

**Comment by childe** [comment]
用Convert filter转一下，转成int



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: libiao163 <notifications@github.com&gt;
发送时间: 2021年2月23日 11:45
收件人: childe/gohangout <gohangout@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[childe/gohangout] 往clickhouse里写数据不能支持Int? (#121)
