### ISSUE TITLE
是否可以支持Input消息的ACK机制

### ISSUE THREAD

**Issue by WideLee** [childe/gohangout#122]
如果从Kafka、Pulsar等MQ作为input输入消息，一般都会对于消息进行一个ACK，如果没处理成功会重复进行推送，但目前的这个框架传递的event是一个map[string]interface{}似乎不太好支持

有没有什么比较好的方案比如所有中间件处理完成后，触发一个input的消息ACK呢？

**Comment by childe** [comment]
我的感觉这是一个比较大的问题。
设想一下，Output 是 ES， 是多个线程并发执行的。后面一批消息已经 Bulk 成功并返回了，但前面一批还没有。那要不要 Ack？
如果一批数据中，一些成功了一些失败了，又要怎么处理，怎么 Ack？
这是一个很大的工程，可能对每个 Output/Input 都要实现不同的策略来适应各种场景。所以当前的想法就是放在每个 Plugin 里面自己去实现 Ack 和重试。比如 Kakfa Input 不管后面处理怎么样，被消费出来后会自动 Commit。 ES Output 会有自己的重试和丢弃策略。

**Comment by WideLee** [comment]
这确实，有时候output也是异步处理的并不是Emit返回了就代表成功消费了，这个主要想解决的场景是比如在重启的时候，可能有些消息读进来了但还没output，不过这个应该可以用Shutdown来解决

**Comment by Dairongpeng** [comment]
问题1：服务重启或者手动停止，kafka消费到的offset是怎么保存的，gohangout服务再次起来后怎么能接着上次的offset继续消费呢？
