### ISSUE TITLE
支持使用Prometheus系统处理消息的监控

### ISSUE THREAD

**Issue by WideLee** [childe/gohangout#123]
目前看到gohangout内部似乎还没有一些接入上报，接入上报能比较方便从外部一些监控看板（Grafana等）看到系统运行的状态，比如每分钟消费消息的条数，处理成功失败次数，CPU/内存占用等

插件相关Metrics
1. 插件处理消息Counter
2. 插件成功处理消息Counter
3. 插件消息处理失败Counter
4. 处理一条消息时间Histogram

系统相关Metrics
1. 系统从input接收到一条消息Counter
2. 系统output输出一条消息Counter
3. 系统出错计数Counter
4. 系统性能基础指标，如CPU核数，利用率、内存等

考虑是否可以增加一个Prometheus的模块，然后系统启动的时候指定--prometheus=true参数来开启某个metrics端口监听

**Comment by childe** [comment]
抱歉没有及时回。感觉最近应该没有精力去做功能增加 :(   有时间了更想把整个逻辑理一下，现在的有点乱。另外考虑下怎么做下 Benchmark ，方便以后有改动了测试一下性能变化。

**Comment by WideLee** [comment]
如果可以的话可以参与共建 😄  目前我们这个也用在生产环境了，遇到问题可以一起梳理进行优化~

另外有个CNCF的开源项目[opentelemetry](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md)里边collector部分似乎也有类似的功能，后边也可以看看要不要出个v2版本然后以opentelemetry collector作为core来进行一些周边的扩展

![image](https://user-images.githubusercontent.com/2196814/109468564-b7666400-7aa7-11eb-91f9-095582604612.png)

**Comment by childe** [comment]
好啊~  我现在工作不负责这块了，如果你们生产在用就太好了~ 哈哈

稍微看了下 opentelemetry, 觉得加到 Collector 里面，就不是 gohangout v2， 而是 opentelemetry 插件，是另外一个项目了~ 
我自己写 Gohangout 的目的一是学习，二是希望有一个非常简单甚至是单一，上手可用的东西。

说到学习这个目的，到是可以加一些 Metric 到插件和整个应用中。我还是想先把 Benchmark 弄一下，如果你对加 Metric 有兴趣，可以一起讨论下怎么搞~
