### ISSUE TITLE
govendor sync 仍然报错

### ISSUE THREAD

**Issue by taojicai** [childe/gohangout#13]
# cd /Users/Charles/re_sxf/go/.cache/govendor/github.com/childe/healer; git reset --hard a298fa4b52427036330ec73aeef3f71e574b17cf
fatal: Could not parse object 'a298fa4b52427036330ec73aeef3f71e574b17cf'.

**Comment by taojicai** [comment]
make 也失败。

**Comment by taojicai** [comment]
release 版本没有文件后缀，怎么启动？

**Comment by childe** [comment]
govendor sync失败, 是我的问题. 忘了把gohangout依赖的kafka库更新到github了.

**Comment by childe** [comment]
linux下面启动不需要后缀吧.

chmod +x gohangout-linux-x64-cdd8fad
./gohangout-linux-x64-cdd8fad --config XXX.yaml
