### ISSUE TITLE
kafka写入clickhouse，json中数字格式错误，导致无法入库

### ISSUE THREAD

**Issue by jsntian** [childe/gohangout#133]
无论是codec: json:not_usenumber还是codec: json，都会报错，ck无法入库
json-iterator/go在转换json数据时数字都转成了float64

**Comment by childe** [comment]
ch里面定义的是什么字段？


给一下你的原始数据，还有ch的表结构。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jsntian ***@***.***&gt;
发送时间: 2021年4月8日 10:51
收件人: childe/gohangout ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[childe/gohangout] kafka写入clickhouse，json中数字格式错误，导致无法入库 (#133)





 
无论是codec: json:not_usenumber还是codec: json，都会报错，ck无法入库
 json-iterator/go在转换json数据时数字都转成了float64

**Comment by jsntian** [comment]
{"isEmulator":0,"batteryTemperature":290,"type":8000,"connectionType":100,"adPushTime":1617764361704,"hardware":"mt6771","deviceType":1,"pass":"254665768715681792","ip":"39.86.37.63","seriaIno":"unknown","batteryScale":100,"screenDensity":"480","cmd":"fusion_track","userType":0,"trackUid":275274762278666240,"clickType":0,"exceptionCode":200,"cid":"102196492","screenWidth":1080,"bssid":"24:6f:8c:38:50:e4","battery":40,"isRooted":0,"mac":"E2:F7:8C:BD:58:C5","manufacturer":"vivo","sid":"E2:F7:8C:BD:58:C5","isDebug":0,"channelAppCode":"244559055853453312","osVersion":"10","vendor":"vivo","osType":1,"screenType":1,"batteryVoltage":3710,"screenHeight":2340}


create TABLE test
(
    day Date,
    logtime DateTime, 
    model String,
    manufacturer String,
    androidVersion Int32,
    pushVersion UInt16,
    ip String,
    country String,
    province String,
    city String, 
    plan String,
    type Int32,
    battery Int32,
    passCode String,
    passAppCode String,
    channelCode String,
    channelAppCode String,
    screenWidth Int32,
    screenHeight Int32,
    reqFailCode String,
    reqFailMsg String,
    exceptionCode Int32,
    title String,
    desc String,
    img String,
    icon String,
    trackUid Int64,
    appName String, 
    userId String,
    ext String,
    contentNum UInt32,
    duration UInt32,
    pageType UInt32, 
    xAxis String,
    yAxis String,
    androidId String,
    clickType Int32,
    yAxis2 String,
    xAxis2 String,
    mac String,
    sid String,
    bid String,
    mcc String,
    mnc String,
    cid String,
    lac String,
    isRooted Int32,
    isProxy Int32,
    isDebug Int32,
    isXposed Int32,
    isEmulator Int32,
    usbState Int32,
    batteryState Int32,
    batteryHealthState Int32,
    batterySurplusCapacity Int32,
    batteryScale Int32,
    batteryVoltage Int32,
    batteryTemperature Int32,
    batteryTechnology String,
    lng String,
    lat String,
    adResult String,
    corporationName String,
    oaid String,
    sourceType Int32,
    userType Int32 
)
ENGINE = MergeTree(day, (day,  logtime), 8192)

报错差不多就是这面这样，也有其它类型不匹配：
 error: type (Int32): unexpected type string

不知道你们那遇没遇到过

**Comment by childe** [comment]
哪个字段啊？

**Comment by jsntian** [comment]
batteryVoltage报错，也不止这一个字段，只要是int32的都报错入不了

**Comment by childe** [comment]
应该使用 json:not_usenumber 
然后用 Convert 把这些字段转成 Int 类型。

**Comment by jsntian** [comment]
我解决了
