### ISSUE TITLE
clickhouse  不能插入数据

### ISSUE THREAD

**Issue by taojicai** [childe/gohangout#14]
ClickHouse server version 19.1.6，无法插入数据，也没有错误日志，input 使用 Stdin，连续10多条 input 记录后程序假死，无法input，clickhouse也没有数据。
outputs:
- Stdout: {}
- Clickhouse:
    table: 'default.app_log'
    hosts:
    - 'tcp://172.16.154.246:8123'
    fields: ['class']
    bulk_actions: 2
    flush_interval: 1
    concurrent: 1

**Comment by childe** [comment]
运行的时候加参数 --logtostderr -v 10 , 打印一些详细的日志看.

**Comment by taojicai** [comment]
8123 是 http 请求方式，改用 900 端口就好了。3X
