### ISSUE TITLE
split 分割字段多了或者少了 都不能分割，能不能改成多了也可以分割？

### ISSUE THREAD

**Issue by rpmdeb** [childe/gohangout#140]
我们的nginx日志是竖线分割的，"xx|xx|xx", 20个字段，我看logstash可以选取指定的字段
`  mutate {
        split => { "message" => "|" }
        add_field => { 
            "time"   => "%{[message][3]}" 
            "request" => "%{[message][7]}" 
            "response" => "%{[message][9]}" 
            "req_len" => "%{[message][5]}" 
            "bytes" => "%{[message][10]}" 
            "up_addr" => "%{[message][17]}" 
        }
        remove_field => [ "message" ]
    }
`
gohangout 的split 必须要分割后的字段跟指定的一样多，不然就分割不了，多了少了 都不行

我觉得是不是应该 message 里面字段比 fields里面的多，就应该继续分割

**Comment by childe** [comment]
嗯好想法 。后面改下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: rpmdeb ***@***.***&gt;
发送时间: 2021年4月22日 11:45
收件人: childe/gohangout ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[childe/gohangout] split 分割字段多了或者少了 都不能分割，能不能改成多了也可以分割？ (#140)





 
我们的nginx日志是竖线分割的，"xx|xx|xx", 20个字段，我看logstash可以选取指定的字段
  mutate { split =&gt; { "message" =&gt; "|" } add_field =&gt; {  "time"   =&gt; "%{[message][3]}"  "request" =&gt; "%{[message][7]}"  "response" =&gt; "%{[message][9]}"  "req_len" =&gt; "%{[message][5]}"  "bytes" =&gt; "%{[message][10]}"  "up_addr" =&gt; "%{[message][17]}"  } remove_field =&gt; [ "message" ] }
 gohangout 的split 必须要分割后的字段跟指定的一样多，不然就分割不了，多了少了 都不行
 
我觉得是不是应该 message 里面字段比 fields里面的多，就应该继续分割

**Comment by childe** [comment]
v1.7.7 做了一些改进
