### ISSUE TITLE
是否支持kerberos化的kafka？

### ISSUE THREAD

**Issue by un-knower** [childe/gohangout#141]
从kafka读取数据，目支持kerberos安全下的kafka吗

**Comment by savico-swee** [comment]
是否支持呢？

**Comment by childe** [comment]
我自己写的 kafka lib https://github.com/childe/healer 不支持，可能有一些其他的库支持吧。可以看一下。https://github.com/childe/gohangout#%E7%AC%AC%E4%B8%89%E6%96%B9-plugin
