### ISSUE TITLE
消费kafka 报错 get metadata  of TOPIC error：EOF

### ISSUE THREAD

**Issue by kingwide** [childe/gohangout#143]
请问这种消费kafka的问题是怎么造成的呢，但是发现似乎并不丢数据
![image](https://user-images.githubusercontent.com/48897677/124742487-5b2cb880-df4f-11eb-8208-e51b52e3f1bd.png)

**Comment by childe** [comment]
按我的经验，eof 都是 server 端主动断开了连接。 server端会有日志说明为什么要断开。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kingwide ***@***.***&gt;
发送时间: 2021年7月7日 18:17
收件人: childe/gohangout ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[childe/gohangout] 消费kafka 报错 get metadata  of TOPIC error：EOF (#143)





 
请问这种消费kafka的问题是怎么造成的呢

**Comment by kingwide** [comment]
请问get metadata gohangout在获取kafka的什么信息，kafka的log里面没有先关报错

**Comment by childe** [comment]
有哪些broker，以及topic有哪些partitions等。
每个kafka broker日志都看了？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kingwide ***@***.***&gt;
发送时间: 2021年7月8日 09:50
收件人: childe/gohangout ***@***.***&gt;
抄送: childe ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[childe/gohangout] 消费kafka 报错 get metadata  of TOPIC error：EOF (#143)





 
请问get metadata gohangout在获取kafka的什么信息，kafka的log里面没有先关报错

**Comment by kingwide** [comment]
是的，kafka 的版本是1.0.0

**Comment by childe** [comment]
你用的什么版本的gohangout





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kingwide ***@***.***&gt;
发送时间: 2021年7月8日 10:07
收件人: childe/gohangout ***@***.***&gt;
抄送: childe ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[childe/gohangout] 消费kafka 报错 get metadata  of TOPIC error：EOF (#143)





 
是的，kafka 的版本是1.0.0

**Comment by kingwide** [comment]
应该是20年初的版本，之后做了些自定义的开发，但是kafka部分的代码没有修改过

**Comment by childe** [comment]
Since this issue has been inactive for a while, I will be closing it. If there is any new information or further discussion needed, please feel free to reopen this issue.
