### ISSUE TITLE
output是否支持按条件输出到不同的elasticsearch集群

### ISSUE THREAD

**Issue by fuping-han** [childe/gohangout#145]
hi 大佬，output是否支持按条件输出到不同的elasticsearch集群

**Comment by huoarter** [comment]
Ealsticsearh:
    if:
        - '{{if .error}}y{{end}}'
Ealsticsearh:
    if:
        - '{{if .error}}n{{end}}'
这样就可以了，条件自己定义呀

**Comment by fuping-han** [comment]
好的，非常感谢
