### ISSUE TITLE
gohangout如何处理es节点写入失败的数据

### ISSUE THREAD

**Issue by fuping-han** [childe/gohangout#146]
hi 请问在es故障(网络或集群自身故障)gohangout如何处理未写入es的数据？这时候会自动提交kafka(input类型为kafka)的offset吗？es故障时间内的数据会丢失吗？thx

**Comment by childe** [comment]
先分两种情况，一种是整个 HTTP 请求就失败了，比如说5XX 了，那这种会整体重试（可配置哪些 HTTPStatus 会重试）。
如果是返回了，会解析响应体，看有没有具体的哪些 Item 失败了，能重试的重试，不能重试的直接丢弃，比如 Mapping 冲突，再怎么重试也不可能成功的，就丢弃了）

**Comment by fuping-han** [comment]
感谢回复

**Comment by fuping-han** [comment]
感谢回复
