### ISSUE TITLE
clickhouse ping error: could not load time location: unknown time zone Asia/Shanghai and no available host

### ISSUE THREAD

**Issue by david-zh-cn** [childe/gohangout#148]
![image](https://user-images.githubusercontent.com/44357168/129207764-e0f67204-b462-4d7b-9c92-c3f5271340e0.png)
E0812 13:42:08.686204       1 clickhouse_output.go:308] clickhouse ping error: could not load time location: unknown time zone Asia/Shanghai
F0812 13:42:08.686397       1 clickhouse_output.go:321] no available host

Could you tell me how to solve it?

**Comment by childe** [comment]
配置文件没有正确的host，都链接失败了
建议看一下 ck 服务端日志



发自我的iPhone


------------------ Original ------------------
From: david-zh-cn ***@***.***&gt;
Date: Thu,Aug 12,2021 9:47 PM
To: childe/gohangout ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [childe/gohangout] clickhouse ping error: could not load time location: unknown time zone Asia/Shanghai and no available host (#148)

**Comment by david-zh-cn** [comment]
I have solved it，but I have another problem.
![image](https://user-images.githubusercontent.com/44357168/129211858-257a67ea-ef50-434d-90f9-b387bcfcb21c.png)

**Comment by david-zh-cn** [comment]
![image](https://user-images.githubusercontent.com/44357168/129212706-55a49a27-2b9d-44d4-a283-e11f00a5905b.png)

**Comment by childe** [comment]
https://github.com/childe/gohangout/commit/55971ab68c5e88cc029268ae53b2b5a4f0e7afaa

这个 Commit 添加了一下对 Datetime64类型的默认值的处理。 试一下？可以自己编译吗？

**Comment by childe** [comment]
Since this issue has been inactive for a while, I will be closing it. If there is any new information or further discussion needed, please feel free to reopen this issue.
