### ISSUE TITLE
max.bytes parameter is too small. This size must be at least as large as the maximum message size the server allows or else it is possible for the producer to send messages larger than the consumer can fetch. If that happens, the consumer can get stuck trying to fetch a large message on a certain partition

### ISSUE THREAD

**Issue by david-zh-cn** [childe/gohangout#149]
![image](https://user-images.githubusercontent.com/44357168/129216730-51bb5b12-548b-4990-b566-a40b1877158a.png)

kafka

![image](https://user-images.githubusercontent.com/44357168/129217017-e0fee507-9eb5-48c0-99ad-e5c0918e2619.png)

**Comment by childe** [comment]
你圈起来的配置，已经够大了，都1G 了。 要么，你先检查一下 Topic 的 max.message.bytes 这个配置是多少？
