### ISSUE TITLE
decompress message error:corrupt input

### ISSUE THREAD

**Issue by xiaoganzi** [childe/gohangout#15]
我消费kafka1.1.0的topic，topic配置lz4压缩，报了decompress message error:corrupt input
这种错误，请问改如何处理？

**Comment by childe** [comment]
应该是解压有问题, 我之前使用的 https://github.com/bkaradzic/go-lz4 , 之前测试还是可以的, 现在用kafka2.0测试失败了, 报了和你一样的错误.

我换一个库试一下吧.

**Comment by childe** [comment]
查下来好像是因为kakfa 自己编码lz4的时候, checksum出错了, 导致别的库不能正确解析.
https://github.com/linkedin/Burrow/issues/494
https://issues.apache.org/jira/browse/KAFKA-3160

现在的办法应该是忽略checksum检查. 我看下怎么处理吧

**Comment by runc** [comment]
楼主何解呢？

**Comment by childe** [comment]
使用 github.com/bkaradzic/go-lz4 这个库的时候, 无论如何都不能解码, 感觉他们的编码方式完全对不上.

使用 github.com/pierrec/lz4 这个库, 是可以解码的, 但是也要修改库的代码, 忽略 checksum 不对的错误才行. 

但一个问题是, 这两个库的效率差太多了, 差了几百倍. pierrec 每秒只能处理2000条数据. 

% go test --bench=. a_test.go
goos: darwin
goarch: amd64
BenchmarkPierrec-4   	    2000	    531523 ns/op
BenchmarkGolz4-4     	 1000000	      1107 ns/op
PASS
ok  	command-line-arguments	2.279s

**Comment by childe** [comment]
有时间了再去看一下 bkaradzic/go-lz4 代码, 希望可以搞定.

**Comment by DukeAnn** [comment]
https://github.com/DukeAnn/gohangout-input-kafka_sarama 这个解决了  lz4 的问题 @childe 望接纳

**Comment by childe** [comment]
> https://github.com/DukeAnn/gohangout-input-kafka_sarama 这个解决了 lz4 的问题 @childe 望接纳

非常感谢, 我放到 Readme 里面.  我还要再看看 Plugin 机制, 能不能有更方便的编译和使用方法.

**Comment by DukeAnn** [comment]
> > https://github.com/DukeAnn/gohangout-input-kafka_sarama 这个解决了 lz4 的问题 @childe 望接纳
> 
> 非常感谢, 我放到 Readme 里面. 我还要再看看 Plugin 机制, 能不能有更方便的编译和使用方法.

不客气，我们也是之前用的你的 java 版本 kafka 写入 ES，性能达到了瓶颈，所以才该换了Golang 。没想到遇到了 kafka 消费 lz4 无法解析的情况，所以把 kafka 包换成了我们常用的包。起初我是直接写在了 input 模块，后来拿出来做成了插件。
性能上测试应该是没有差异，写入速度以我们目前的场景达到了每分钟 四千五百万

**Comment by childe** [comment]
https://github.com/huangjacky/gohangout-input-kafkago
https://github.com/DukeAnn/gohangout-input-kafka_sarama

没精力继续支持自己写的 Kafka 库了。用上面这两个吧。 把 Issue 关掉了。
