### ISSUE TITLE
sprig 函数结果不符合预期

### ISSUE THREAD

**Issue by aragornzhao** [childe/gohangout#150]
![image](https://user-images.githubusercontent.com/20312048/132475125-ecf1f4ae-24b0-4ae6-b166-9dba42077a36.png)
如图所示代码
x.(int64) 当 x为interface{} 时， 转换基本是失败的。 导致不会产生预期的结果

**Comment by childe** [comment]
@aragornzhao 先使用 Convert 转换一下。
