### ISSUE TITLE
kafka lz4 & field json parse  

### ISSUE THREAD

**Issue by braior** [childe/gohangout#156]
在这里首先非常感谢作者开源该优秀的软件，解决了公司因logstash带来的资源浪费的问题
在重度使用过程中遇到以下问题：
1、healer实现的Kafka客户端无法消费lz4格式的日志，有作者通过插件解决了该问题，但是该插件没有适配kafka鉴权问题  https://github.com/huangjacky/gohangout-input-kafkago
2、在field字段解析过程中没有适配not_usenumber

**Comment by childe** [comment]
谢谢反馈。

1. LZ4的问题我再看看，LZ4的压缩和速度都很好，争取看看怎么支持好
2. 不太明白啥意思，有例子不？

**Comment by wsjhk** [comment]
目前好像还不支持zstd压缩格式的日志是吗？开启zstd压缩后gohangout无法消费消息。

**Comment by childe** [comment]
lz4 已经支持。

zstd 还不支持。
