### ISSUE TITLE
输入到clickhouse时，如何指定字段的值输入

### ISSUE THREAD

**Issue by jieshier** [childe/gohangout#162]
--日志例子：
{
    "http_host":"www.baidu.com",
    "fields":{
        "log_source":"www.baidu.com",
    },
}

--现在我要指定 http_host 值等于 ”www.baidu.com“ 的数据才插入到clickhouse中

--我的gohangout配置测试：
outputs:
    - Clickhouse:
        if:
                - 'Contains($.http_host,"www.baidu.com")'
                #- '{{if eq .http_host "www.baidu.com"}}y{{end}}'
                #- 'EQ(http_host,"www.baidu.com")'
                table: 'xxx'
                conn_max_life_time: 1800
                username: default
                hosts:
                - 'tcp://localhost:9000'
                bulk_actions: 1000
                flush_interval: 30

--以上测试都试过了不行，请问应该怎么编写，感谢🙏

**Comment by childe** [comment]
`'EQ($.http_host,"www.baidu.com")'`
