### ISSUE TITLE
ES 8.1.0   contains an unknown parameter [_type]"}],"type":"illegal_argument_exception",

### ISSUE THREAD

**Issue by zcola** [childe/gohangout#166]
hangout 版本 1.7.8

 elasticsearch_output.go:145] could NOT get errors in response:{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}

**Comment by childe** [comment]
应该是需要配置一下 es_version: 8

**Comment by zcola** [comment]
> 应该是需要配置一下 es_version: 8

11
