### ISSUE TITLE
带条件的drop不符合预期

### ISSUE THREAD

**Issue by ermazi** [childe/gohangout#169]
无论条件是什么，event都会被drop掉，仔细看，drop filter没有判断条件的逻辑

小修一下：
#168

**Comment by childe** [comment]
并不是你说的这样。
如果你觉得有问题，请至少给出例子。

**Comment by ermazi** [comment]
> 并不是你说的这样。 如果你觉得有问题，请至少给出例子。

哦，只是整了一下单元测试，发现并不生效，刚刚细看了一下，condition时在filterbox统一处理的，drop的单测测不出来，不好意思，😂
