### ISSUE TITLE
支持像logstash中的topic正则么？

### ISSUE THREAD

**Issue by drings-liu** [childe/gohangout#179]
如logstash input 中的topic正则， topics_pattern =>[test-.*]
输出中的 index => "%{[@metadata][kafka][topic]}-%{+YYYY-MM-dd}"这样的配置么？

**Comment by childe** [comment]
Input 这个不支持，可以看一下其他的 Kafka Input Plugin。

Output 在 v1.8.2 里面支持了。 `%{@metadata}{kafka}{topic}-%{+2006-01-02}`
