### ISSUE TITLE
如果input是json array，能否拆分为多个event？

### ISSUE THREAD

**Issue by gotosre** [childe/gohangout#181]
现在数据源是
[{log1},{log2},...,{logN}]

json解析后，能否生成多个events？

**Comment by childe** [comment]
不能。确定是这种格式？看着不太通用，有点难搞。

**Comment by childe** [comment]
需要自己写 Filter 来解析

**Comment by MrLiukang** [comment]
@gotosre 我这遇到了，不过是自己写了个input来专门处理这个问题的

**Comment by childe** [comment]
Since this issue has been inactive for a while, I will be closing it. If there is any new information or further discussion needed, please feel free to reopen this issue.
