### ISSUE TITLE
json 转换使用not_usenumber 丢失精度问题

### ISSUE THREAD

**Issue by zhangliguo20180529** [childe/gohangout#183]
最近在使用中发现，json转换出现丢失精度问题
我的使用场景是，使用gohangout消费kafka的json数据，再把数据推送到elastic，
源字段 {”message":{"connecter_thread_http_result_start":1655877290393} }
使用如下代码
- Json:
          field: message
          not_usenumber: true
转换后写入到elastic {“connecter_thread_http_result_start”:1655877300000}，已排除elastic本身丢精度问题

**Comment by childe** [comment]
要使用 usenunber，本来 Json 就有精度问题，这就是 Golang 里面  usenumber 的意义所在。
