### ISSUE TITLE
字符串分割

### ISSUE THREAD

**Issue by lvzhongwen12138** [childe/gohangout#187]
{"upstream_addr":"14.29.191.101:30782, 14.29.191.101:30782, 14.29.191.101:30782, 14.29.191.101:30782, 14.29.191.101:30782, 14.29.191.101:30782",
"upstream_response_time":"0.002, 0.003, 0.002, 0.002, 0.002, 0.003"}
类似这样的数据，我想以逗号（,）切割upstream_addr和upstream_response_time的value，然后只保留最后一个数据，即切割后的数据为：{"upstream_addr":"14.29.191.101:30782","upstream_response_time":"0.003"}
请问我用split应该如果写？

**Comment by childe** [comment]
@lvzhongwen12138 使用 Grok
