### ISSUE TITLE
scan rows error: sql: expected 6 destination arguments in Scan, not 4

### ISSUE THREAD

**Issue by xxxxzr** [childe/gohangout#19]
你好，我想用gohangout从kafka往clickhouse导数,报了这个错
`E0327 17:32:50.996244   21738 clickhouse_output.go:75] scan rows error: sql: expected 6 destination arguments in Scan, not 4`
请问这个错是什么原因导致的。。
下面是我的配置
inputs:
    - Stdin:
        codec: json
    - Kafka:
        codec: json
        topic:
            k_ads_event_stat: 1
        consumer_settings:
            group.id: gohangout.kafka
            bootstrap.servers: "dev-kafka-01.dev:9092"
            from.beginning: true

filters:                  
    - Add:
        fields:
            p_date: "${(beginTime)?substring(0, 10)}"
            

outputs:
    - Clickhouse:
        table: 'default.kafka_test'
        hosts:
        - 'tcp://xx.xx.xx.xx:9000'
        fields: ['p_date', 'beginTime','endTime', 'advertiserId', 'campaignId', 'adGroupId', 'creativeId', 'spotId', 'showCount', 'clickCount', 'playCount']
        username: 'default'
        password: ''
        bulk_actions: 1000
        flush_interval: 30
        concurrent: 1

**Comment by childe** [comment]
对Clickhouse和数据库不太熟悉, 应该是每个表的属性不一样, 在 desc table XX 的时候, 返回的列数不是4个导致这个错误. 

明儿看一下怎么修复这个问题, 适应不同的表.

**Comment by xxxxzr** [comment]
> 对Clickhouse和数据库不太熟悉, 应该是每个表的属性不一样, 在 desc table XX 的时候, 返回的结果不是4"列", 导致这个错误.
> 
> 我期望的返回是四列, 分别是	column type	defaultWay	defaultExpression
> 
> 明儿看一下怎么修复这个问题, 适应不同的表.

对我也看到这边了，但是对go不太熟。。我看从kafka拉数据是正常的，就差这一步了

**Comment by childe** [comment]
@xxxxzr 加下微信好吗? 64973150 我看clickhouse create table 默认是四列,https://clickhouse.yandex/docs/en/query_language/create/  不知道为啥你的是6列, 想微信沟通方便些.

**Comment by childe** [comment]
是我看错了, 还可能有 compression_codec 等配置吧. 我处理下代码.

**Comment by childe** [comment]
fix a52bf5e4b50b1166e5567d5d424830f5237e8f60

**Comment by xxxxzr** [comment]
nice . 已经修复～

**Comment by songlichaofightting** [comment]
哥们救命啊，我也遇到一样一样的问题了，怎么整的啊

**Comment by childe** [comment]
https://github.com/childe/gohangout/releases/tag/v1.2.5
