### ISSUE TITLE
output到clickhouse时，能否使用if条件

### ISSUE THREAD

**Issue by w38351479** [childe/gohangout#196]
output到clickhouse时，能否使用if条件，不同的消息，根据规则写入不同的clickhouse分布式表中（如Nginx、Tomcat、Apache、MySQL等日志），进行分类。或者有类型的实现办法吗？谢谢！

**Comment by childe** [comment]
应该是可以的，直接使用 if 就可以。

如果还有困难，给出具体的例子看下吧。

**Comment by w38351479** [comment]
可以
