### ISSUE TITLE
一直在try to join group

### ISSUE THREAD

**Issue by lynnhuel** [childe/gohangout#2]
failed to send heartbeat:The group is rebalancing, so a rejoin is needed.
我之前用的hangout，配置文件做了修改之后，运行了gohangout，然后就一直报上面的错误，打开v5后，详细信息显示，可以找到后端es和前端kafka，可以commit offset，就是不能加入group，一直重试

**Comment by childe** [comment]
@lynnhuel  可以把 Log 发我看一下吗? 如果能commit offset却不能加入group, 那应该是个BUG.. :(

你是用的哪个版本? release里面的v0.0.1是最新打包的版本.

**Comment by lynnhuel** [comment]
I1112 10:29:46.437399    1246 simple_consumer.go:95] got leader broker 10.10.10.29:9092 with id 29
I1112 10:29:46.437205    1246 simple_consumer.go:75] leader ID of [domain.xxx][8] is 28
I1112 10:29:46.437464    1246 simple_consumer.go:95] got leader broker 10.10.10.27:9092 with id 27
I1112 10:29:46.437467    1246 simple_consumer.go:75] leader ID of [domain.xxx][3] is 29
I1112 10:29:46.437494    1246 simple_consumer.go:75] leader ID of [domain.xxx][11] is 28
I1112 10:29:46.437540    1246 simple_consumer.go:95] got leader broker 10.10.10.28:9092 with id 28
I1112 10:29:46.437609    1246 simple_consumer.go:95] got leader broker 10.10.10.28:9092 with id 28
I1112 10:29:46.437624    1246 simple_consumer.go:75] leader ID of [domain.xxx][6] is 29
I1112 10:29:46.437662    1246 simple_consumer.go:75] leader ID of [domain.xxx][2] is 28
I1112 10:29:46.437730    1246 simple_consumer.go:95] got leader broker 10.10.10.28:9092 with id 28
I1112 10:29:46.437763    1246 simple_consumer.go:95] got leader broker 10.10.10.29:9092 with id 29
I1112 10:29:46.437796    1246 simple_consumer.go:75] leader ID of [domain.xxx][13] is 27
I1112 10:29:46.437833    1246 simple_consumer.go:95] got leader broker 10.10.10.29:9092 with id 29
I1112 10:29:46.437864    1246 simple_consumer.go:95] got leader broker 10.10.10.28:9092 with id 28
I1112 10:29:46.437931    1246 simple_consumer.go:75] leader ID of [domain.xxx][10] is 27
I1112 10:29:46.437964    1246 simple_consumer.go:95] got leader broker 10.10.10.27:9092 with id 27
I1112 10:29:46.438117    1246 simple_consumer.go:95] got leader broker 10.10.10.27:9092 with id 27
I1112 10:29:46.438126    1246 simple_consumer.go:75] leader ID of [domain.xxx][7] is 27
I1112 10:29:46.438325    1246 simple_consumer.go:95] got leader broker 10.10.10.27:9092 with id 27
I1112 10:29:46.440009    1246 simple_consumer.go:179] [domain.xxx][0] offset :-1
I1112 10:29:46.440273    1246 brokers.go:50] got 3 brokers
I1112 10:29:46.440291    1246 brokers.go:53] 27 10.10.10.27:9092
I1112 10:29:46.440303    1246 brokers.go:53] 28 10.10.10.28:9092
I1112 10:29:46.440313    1246 brokers.go:53] 29 10.10.10.29:9092
I1112 10:29:46.441048    1246 group_consumer.go:130] coordinator for group[domain.xxx_go]:10.10.10.29:9092
I1112 10:29:46.441064    1246 group_consumer.go:167] try to join group domain.xxx_go
I1112 10:29:46.441203    1246 simple_consumer.go:75] leader ID of [domain.xxx][4] is 27
I1112 10:29:46.441253    1246 simple_consumer.go:179] [domain.xxx][8] offset :-1
I1112 10:29:46.441295    1246 simple_consumer.go:75] leader ID of [domain.xxx][14] is 28
I1112 10:29:46.441389    1246 simple_consumer.go:95] got leader broker 10.10.10.27:9092 with id 27
I1112 10:29:46.441580    1246 simple_consumer.go:95] got leader broker 10.10.10.28:9092 with id 28
I1112 10:29:46.441621    1246 simple_consumer.go:75] leader ID of [domain.xxx][9] is 29
I1112 10:29:46.441780    1246 simple_consumer.go:179] [domain.xxx][5] offset :-1
I1112 10:29:46.441821    1246 simple_consumer.go:95] got leader broker 10.10.10.29:9092 with id 29
I1112 10:29:46.441949    1246 simple_consumer.go:179] [domain.xxx][12] offset :-1
I1112 10:29:46.442096    1246 simple_consumer.go:179] [domain.xxx][6] offset :-1
I1112 10:29:46.442135    1246 simple_consumer.go:179] [domain.xxx][1] offset :-1
I1112 10:29:46.442096    1246 simple_consumer.go:179] [domain.xxx][11] offset :-1
I1112 10:29:46.442407    1246 simple_consumer.go:179] [domain.xxx][3] offset :-1
I1112 10:29:46.442408    1246 simple_consumer.go:179] [domain.xxx][13] offset :-1
I1112 10:29:46.442460    1246 simple_consumer.go:179] [domain.xxx][10] offset :-1
I1112 10:29:46.442482    1246 simple_consumer.go:179] [domain.xxx][7] offset :-1
I1112 10:29:46.442463    1246 simple_consumer.go:192] consume [domain.xxx][8] from 63459060
I1112 10:29:46.442797    1246 simple_consumer.go:192] consume [domain.xxx][5] from 63470946
I1112 10:29:46.443005    1246 simple_consumer.go:179] [domain.xxx][2] offset :-1
I1112 10:29:46.443202    1246 simple_consumer.go:179] [domain.xxx][14] offset :-1
I1112 10:29:46.443231    1246 simple_consumer.go:192] consume [domain.xxx][6] from 63472093
I1112 10:29:46.443286    1246 simple_consumer.go:179] [domain.xxx][9] offset :-1
I1112 10:29:46.443310    1246 simple_consumer.go:179] [domain.xxx][4] offset :-1
I1112 10:29:46.443389    1246 simple_consumer.go:192] consume [domain.xxx][11] from 63463666
I1112 10:29:46.443658    1246 simple_consumer.go:192] consume [domain.xxx][0] from 63476911
I1112 10:29:46.443780    1246 simple_consumer.go:192] consume [domain.xxx][3] from 63473654
I1112 10:29:46.444151    1246 simple_consumer.go:192] consume [domain.xxx][2] from 63487104
I1112 10:29:46.444159    1246 simple_consumer.go:192] consume [domain.xxx][14] from 63481844
I1112 10:29:46.444231    1246 simple_consumer.go:192] consume [domain.xxx][12] from 63463913
I1112 10:29:46.444458    1246 simple_consumer.go:192] consume [domain.xxx][4] from 63522286
I1112 10:29:46.444532    1246 simple_consumer.go:192] consume [domain.xxx][7] from 63539161
I1112 10:29:46.444691    1246 simple_consumer.go:192] consume [domain.xxx][1] from 63542510
I1112 10:29:46.444770    1246 simple_consumer.go:192] consume [domain.xxx][10] from 63533516
I1112 10:29:46.444977    1246 simple_consumer.go:192] consume [domain.xxx][13] from 63537223
I1112 10:29:46.445620    1246 simple_consumer.go:192] consume [domain.xxx][9] from 63471859
E1112 10:29:49.395667    1246 group_consumer.go:389] failed to send heartbeat:The group is rebalancing, so a rejoin is needed.
I1112 10:29:49.395713    1246 group_consumer.go:167] try to join group domain.xxx_go
E1112 10:29:49.405052    1246 group_consumer.go:389] failed to send heartbeat:The group is rebalancing, so a rejoin is needed.
I1112 10:29:49.405071    1246 group_consumer.go:167] try to join group domain.xxx_go
E1112 10:29:49.411329    1246 group_consumer.go:389] failed to send heartbeat:The group is rebalancing, so a rejoin is needed.
I1112 10:29:49.411349    1246 group_consumer.go:167] try to join group domain.xxx_go
E1112 10:29:49.418589    1246 group_consumer.go:389] failed to send heartbeat:The group is rebalancing, so a rejoin is needed.
I1112 10:29:49.418617    1246 group_consumer.go:167] try to join group domain.xxx_go
E1112 10:29:49.428957    1246 group_consumer.go:389] failed to send heartbeat:The group is rebalancing, so a rejoin is needed.
I1112 10:29:49.428977    1246 group_consumer.go:167] try to join group domain.xxx_go

**Comment by lynnhuel** [comment]
生产环境，用domain.xxx替换。用的是最新版。之前用hangout内存占用过大。今天刚看到新项目，就想试试

**Comment by lynnhuel** [comment]
goroutine数换成1后，读取正常。后端es  不可达，no available host

**Comment by lynnhuel** [comment]
curl http://10.0.0.202:9200正常， curl http://10.0.0.202:9200/_bulk，No feature for name [_bulk]

**Comment by childe** [comment]
@lynnhuel 直接 curl http://10.0.0.202:9200/_bulk  报错是正常现象, 因为_bulk用GET方法是不行的.

hosts里面配置的时候不要用_bulk, 正确的像下面这样

        hosts:
            - http://10.0.0.202:9200

错误的如下:

        hosts:
            - http://10.0.0.202:9200/_bulk

给我看下你的配置文件吧?

**Comment by lynnhuel** [comment]
inputs:
    - Kafka:
        codec: json
        topic:
            domain.xxx: 1
        consumer_settings:
            group.id: domain.xxx_go
            bootstrap.servers: "10.10.10.29:9092,10.10.10.27:9092,10.10.10.28:9092"
            auto.commit.interval.ms: 5000
outputs:
    - Elasticsearch:
        hosts:
            - http://10.0.0.202:9200
            - http://10.2.1.72:9200
            - http://10.2.1.55:9200
        index: 'filebeat_%{type}_access-%{+2018.11.11}'
        concurrent: 2

**Comment by lynnhuel** [comment]
```
inputs:
    - Kafka:
        codec: json
        topic:
            domain.xxx: 1
        consumer_settings:
            group.id: domain.xxx_go
            bootstrap.servers: "10.10.10.29:9092,10.10.10.27:9092,10.10.10.28:9092"
            auto.commit.interval.ms: 5000
outputs:
    - Elasticsearch:
        hosts:
            - http://10.0.0.202:9200
            - http://10.2.1.72:9200
            - http://10.2.1.55:9200
        index: 'filebeat_%{type}_access-%{+2018.11.11}'
        concurrent: 2
```
配置应该是没问题的，或许跟我的es版本有关系？

**Comment by childe** [comment]
关于多个goroutine出错, 只看3秒钟的日志看不出来是"出错"还是正常的rejoin. 
一次join默认大概会用30秒, 如果多goroutine, 后面的gorouting加入group的时候,  的确会造成rejoin, 但稳定之后应该就好了, 不会一直不停的rejoin. 

no available host 的报错, 一时没看出来啥问题, 确认在跑gohangout的机器上面,  curl http://10.0.0.202:9200 是正确返回的?  
把no available host 前后的日志发我看一下?

**Comment by childe** [comment]
@lynnhuel 

下面这个配置改一下试试看, 不知道你的ES版本是啥, 怀疑是索引名字不正确导致_bulk失败

    index: 'filebeat_%{type}_access-%{+2018.11.11}'

改成 

    index: 'filebeat_access-%{+2006.01.02}'

**Comment by lynnhuel** [comment]
I1112 11:33:03.260693   10767 bulk_http.go:272] try to bulk with host (http://10.2.1.55:9200/_bulk)
I1112 11:33:03.260704   10767 bulk_http.go:304] request size:3164072
I1112 11:33:03.329418   10767 bulk_http.go:338] request with http://10.2.1.55:9200/_bulk error: Post http://10.2.1.55:9200/_bulk: read tcp 10.10.10.27:48221->10.2.1.55:9200: read: connection reset by peer
E1112 11:33:03.329459   10767 bulk_http.go:282] bulk failed with http://10.2.1.55:9200/_bulk
I1112 11:33:03.329482   10767 bulk_http.go:272] try to bulk with host (http://10.0.0.202:9200/_bulk)
I1112 11:33:03.329493   10767 bulk_http.go:304] request size:3164072
I1112 11:33:03.401832   10767 bulk_http.go:338] request with http://10.0.0.202:9200/_bulk error: Post http://10.0.0.202:9200/_bulk: read tcp 10.10.10.27:58185->10.0.0.202:9200: read: connection reset by peer
E1112 11:33:03.401875   10767 bulk_http.go:282] bulk failed with http://10.0.0.202:9200/_bulk
I1112 11:33:03.401930   10767 bulk_http.go:272] try to bulk with host (http://10.2.1.72:9200/_bulk)
I1112 11:33:03.401947   10767 bulk_http.go:304] request size:3164072
I1112 11:33:03.471016   10767 bulk_http.go:338] request with http://10.2.1.72:9200/_bulk error: Post http://10.2.1.72:9200/_bulk: read tcp 10.10.10.27:59015->10.2.1.72:9200: read: connection reset by peer
E1112 11:33:03.471059   10767 bulk_http.go:282] bulk failed with http://10.2.1.72:9200/_bulk
I1112 11:33:03.471083   10767 bulk_http.go:272] try to bulk with host (http://10.2.1.55:9200/_bulk)
I1112 11:33:03.471094   10767 bulk_http.go:304] request size:3164072
I1112 11:33:03.540175   10767 bulk_http.go:338] request with http://10.2.1.55:9200/_bulk error: Post http://10.2.1.55:9200/_bulk: read tcp 10.10.10.27:48227->10.2.1.55:9200: read: connection reset by peer
E1112 11:33:03.540219   10767 bulk_http.go:282] bulk failed with http://10.2.1.55:9200/_bulk
I1112 11:33:03.540243   10767 bulk_http.go:272] try to bulk with host (http://10.0.0.202:9200/_bulk)
I1112 11:33:03.540254   10767 bulk_http.go:304] request size:3164072
I1112 11:33:03.607825   10767 bulk_http.go:338] request with http://10.0.0.202:9200/_bulk error: Post http://10.0.0.202:9200/_bulk: read tcp 10.10.10.27:58191->10.0.0.202:9200: read: connection reset by peer
E1112 11:33:03.607861   10767 bulk_http.go:282] bulk failed with http://10.0.0.202:9200/_bulk
I1112 11:33:03.607910   10767 bulk_http.go:272] try to bulk with host (http://10.2.1.72:9200/_bulk)
I1112 11:33:03.607926   10767 bulk_http.go:304] request size:3164072
I1112 11:33:03.679497   10767 bulk_http.go:338] request with http://10.2.1.72:9200/_bulk error: Post http://10.2.1.72:9200/_bulk: read tcp 10.10.10.27:59021->10.2.1.72:9200: read: connection reset by peer
E1112 11:33:03.679538   10767 bulk_http.go:282] bulk failed with http://10.2.1.72:9200/_bulk
I1112 11:33:03.679552   10767 bulk_http.go:267] no available host, wait for 30s

**Comment by lynnhuel** [comment]
@childe 改了index也是一样的。我先研究研究，有情况了再来找你

**Comment by childe** [comment]
@lynnhuel 
我的建议是

1. 先看一下ES日志, 有没有什么报错.
2. tcpdump看下网络层面有什么问题.

个人感觉, 这两步下来, 基本上能大概定位.

**Comment by childe** [comment]
@lynnhuel 如果你自己编译了, 那可以把报错的地方注释掉, 或者改成适合你版本的. 那里的主要目的是打印日志(也有部分重试的逻辑在里面)

**Comment by lynnhuel** [comment]
@childe 我编译的时候没报错，运行时候提示flag redefined: log_dir  这是什么原因呢

**Comment by childe** [comment]
log_dir这个参数重复定义了,  这个问题我也不能一下子就知道在哪里重复定义了.

这个参数正常来看, 是在 github.com/golang/glog 这个库里面的. 

我怀疑, 我写的 healer 这个库, 你不是用的最新的. 因为我之前可能因为flag的问题改过一些东西, 你pull一下最新的看吧.

**Comment by gitzh2017** [comment]
您好，通过索引里面的字段设置索引名字，现在有没有方法可以解决

**Comment by childe** [comment]
@gitzh2017 新开了了个 https://github.com/childe/gohangout/issues/16
