### ISSUE TITLE
uncompress records bytes error

### ISSUE THREAD

**Issue by jinmuyano** [childe/gohangout#203]
E0114 17:45:39.447080    3997 fetch_response.go:525] uncompress records bytes error: uncompress gzip records error: unexpected EOF
E0114 17:45:39.447118    3997 simple_consumer.go:448] consumer nginxlog[0] error:uncompress records bytes error: uncompress gzip records error: unexpected EOF

**Comment by childe** [comment]
看这个报错的意思是说解压 Gzip 消息的时候，数据异常中断。不确定是代码有问题，还是数据本身有问题。可以以下两步看看。

1. 用 Kafka 官方的消费者消费一下看看有没有问题
2. 运行 gohangout 的时候，加参数 -v 10 看一下详细的日志

**Comment by Cerberuxx** [comment]
@jinmuyano 请问这个问题解决了吗？我也碰到同样的报错了加上-v 10也没有看到可用的报错信息

**Comment by childe** [comment]
> @jinmuyano 请问这个问题解决了吗？我也碰到同样的报错了加上-v 10也没有看到可用的报错信息

没有。
日志默认都打印到文件，不输出到屏幕。

**Comment by childe** [comment]
fix in https://github.com/childe/healer/commit/2caca95d323d725033a6b2d7620c774c5bcbf200
