### ISSUE TITLE
关于out put的问题

### ISSUE THREAD

**Issue by a33151** [childe/gohangout#205]
日志格式如下:

![image](https://user-images.githubusercontent.com/39002914/218520327-e346be7f-11e9-4bc5-a7d1-f3c54af474bd.png)

但是使用这样的格式

outputs:
  - Elasticsearch:
      hosts:
        - "http://aaaaa@10.104.1.1:9200"
        index: 'mytest-%{message.app}-%{tags.k8s.namespace.name}-%{+2006.01.02}'

其中字段 message.app   tags.k8s.namespace.name 在ES采集到的index为null 请问是我的配置问题吗 烦请指教 非常感谢!

**Comment by childe** [comment]
试一下

```
index: 'mytest-%{message}{app}-%{tags}{k8s}{namespace}{name}-%{+2006.01.02}'
```

**Comment by a33151** [comment]
我把字段给rename成 k8s_namespace_name 使用如下格式可以了,非常感谢!

index: 'mytest-%{message}{app}-%{tags}{k8s_namespace_name}-%{+2006.01.02}'
