### ISSUE TITLE
my kafka version is 1.0.0，kafka server got the err:Magic v0 does not support record headers

### ISSUE THREAD

**Issue by wjzsuperman** [childe/gohangout#21]
kafka get the error like followers:
Error when handling request {replica_id=-1,max_wait_time=100,min_bytes=1,topics=[{topic=wj.sleuth.test,partitions=[{partition=17,fetch_offset=0,max_bytes=10485760}]}]} (kafka.server.KafkaApis)
java.lang.IllegalArgumentException: Magic v0 does not support record headers
at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:403)
at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:586)

ghangout got the err:

E0410 14:14:52.967678 53245 fetch_response.go:255] The server experienced an unexpected error when processing the request
I0410 14:14:52.967687 53245 simple_consumer.go:341] consumer wj.sleuth.test[29] error:The server experienced an unexpected error when processing the request
I0410 14:14:52.967722 53245 simple_consumer.go:309] simple consumer stop consuming wj.sleuth.test[29]
E0410 14:14:52.968932 53245 fetch_response.go:255] The server experienced an unexpected error when processing the request

**Comment by childe** [comment]
看起来是协议上面有问题. 
你是用的哪个版本的gohangout? 我测一下kafka 1.0.0 取数据

**Comment by childe** [comment]
https://issues.apache.org/jira/browse/KAFKA-6739?src=confmacro 
kafka 1.0.0 有这个BUG, 有考虑升级吗? :)

**Comment by childe** [comment]
client这边也可以升级使用新的协议解决这个问题, 但目前没有精力去改代码了. (这个改动会比较大)

**Comment by MrXianSen** [comment]
> client这边也可以升级使用新的协议解决这个问题, 但目前没有精力去改代码了. (这个改动会比较大)

Magic v0 does not support record headers
请问rdhakfa能支持kafka2.2.1吗？

**Comment by childe** [comment]
rdhakfa是啥?
