### ISSUE TITLE
有打算支持SCRAM 256/512的认证么

### ISSUE THREAD

**Issue by bj1116** [childe/gohangout#213]
有打算支持SCRAM 256/512的认证么

**Comment by childe** [comment]
> 

这些认证其实都想搞的，但现在精力不太够。

**Comment by bj1116** [comment]
要不考虑下直接用sarama进行input和output，不用healer，这样少维护一个库，最近这边有时间，可以测试下:-)

**Comment by childe** [comment]
> 要不考虑下直接用sarama进行input和output，不用healer，这样少维护一个库，最近这边有时间，可以测试下:-)

可以啊，你直接换成 sarama 就可以~
