### ISSUE TITLE
kafka output ，compress.type配置压缩为lz4，发送不成功

### ISSUE THREAD

**Issue by bj1116** [childe/gohangout#214]
kafka output ，compress.type配置压缩为lz4，发送不成功

**Comment by childe** [comment]
> kafka output ，compress.type配置压缩为lz4，发送不成功

我晚点看一下。另外，有没有具体的报错？

**Comment by bj1116** [comment]
10304 simple_producer.go:262] decode produce response error: The server experienced an unexpected error when processing the request

**Comment by childe** [comment]
可能是之前版本的Healer，编码Produce request里面的Message，使用的version 1 的Message导致，后来有升级，先关闭Issue。
