### ISSUE TITLE
any plan to support output loki?

### ISSUE THREAD

**Issue by gotosre** [childe/gohangout#218]
any plan to support output loki?

**Comment by childe** [comment]
not yet



发自我的iPhone


------------------ Original ------------------
From: gotosre ***@***.***&gt;
Date: Fri,May 26,2023 10:13 AM
To: childe/gohangout ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [childe/gohangout] any plan to support output loki? (Issue #218)





 
any plan to support output loki?

**Comment by childe** [comment]
Since this issue has been inactive for a while, I will be closing it. If there is any new information or further discussion needed, please feel free to reopen this issue.
