### ISSUE TITLE
Logging without becoming coupled to a particular logging implementation

### ISSUE THREAD

**Issue by ColinChamber** [childe/gohangout#229]
How about using https://github.com/go-logr/logr? @childe

**Comment by childe** [comment]
在一些基础库中，我想使用 logr ，比如 https://github.com/childe/healer

gohangout 是一个 application，我觉得作者选一个 Log 库来用，问题不大。但 glog 有 些缺陷，我想换成 klog 了。

**Comment by childe** [comment]
已经替换成 klog，感谢 @ColinChamber
