### ISSUE TITLE
没有正常解析数据

### ISSUE THREAD

**Issue by yasincyx** [childe/gohangout#237]
![6610bcb78a47b0321bc1058c0e202b1](https://github.com/childe/gohangout/assets/72586258/77368930-ee6c-428d-9328-99ae8e6e5492)
大佬，我这边解析没有报错，但是看着没有正常解析。打印了正则之后就一直是try to bulk with host了
用stdout出来对应的数据有正常显示
![image](https://github.com/childe/gohangout/assets/72586258/25349c39-8ab3-4fe2-bcf5-159698dee2dd)

大佬有空的话麻烦cc

**Comment by childe** [comment]
搞定啦？
