### ISSUE TITLE
支持将Json Array 转换成多行到CK吗？

### ISSUE THREAD

**Issue by chunxinhou** [childe/gohangout#242]
比如如下JSON

```
[
    {
    "name":"w",
    "age":99
    },
    {
    "name":"h",
    "age":88
    }
]
```
- 输出
 
| name | age | 
|-------|-------|
| w | 99 | 
| h | 88 |

**Comment by childe** [comment]
抱歉漏掉消息了，写了一个例子，你可以参考下。

https://github.com/childe/gohangout-plugin-examples/tree/master/gohangout-filter-flat-json
