### ISSUE TITLE
kafka多个主题，插入多个clickhouse表

### ISSUE THREAD

**Issue by Evilglory1371** [childe/gohangout#245]
怎么使指定的kafka主题 插入指定的clickhouse表中？

**Comment by childe** [comment]
1. 使用 [decorate_events](https://github.com/childe/gohangout?tab=readme-ov-file#decorate_events) 将kafka topic也添加到数据中
2. 在output中使用 [if](https://github.com/childe/gohangout?tab=readme-ov-file#if) 语法

但我还是推荐使用多个 gohangout实例，更清楚一些吧。
