### ISSUE TITLE
input和output都是Kafka的时候output的Kafka报错

### ISSUE THREAD

**Issue by lucky0137** [childe/gohangout#255]
如题，当input是Kafka，output也是Kafka的时候，output中的Kafka报错
F1021 11:23:24.038821  318249 kafka_output.go:63] could not create kafka producer: update current simple consumer of byb_log error: get metadata of byb_log error: byb_log error: UNKNOWN_TOPIC_OR_PARTITION:This server does not host this topic-partition.

测试版本
v1.10.9
kafka
v3.7

**Comment by childe** [comment]
v1.10.11 处理了这个问题，有问题再开吧。
