### ISSUE TITLE
gohangout实例缩容时运行中的实例出现kafka的panic报错

### ISSUE THREAD

**Issue by mdh67899** [childe/gohangout#256]
您好，我现有环境是v1.4.9版本，使用场景是从kafka读取消息，json处理后写入到es

我升级到最新的gohangout版本：v1.10.12时，发现gohangout实例缩容的情况下，现有存活的gohangout进程会打印出一些kafka panic进程异常退出掉，附件是gohangout进程的全部日志，辛苦帮忙定位一下是否是github.com/childe/healer依赖是否有问题，谢谢

[gohangout.txt](https://github.com/user-attachments/files/17552806/gohangout.txt)

**Comment by childe** [comment]
感谢提供日志，我看下。

**Comment by childe** [comment]
如果容易复现的话，能不能tcpdump出来一个dump文件发我？

**Comment by childe** [comment]
OK，有先关了哈，有问题再开~
