### ISSUE TITLE
有输出日志按照天或者大小滚动的功能吗?

### ISSUE THREAD

**Issue by devNullgh** [childe/gohangout#30]
大家平常打印日志是怎么用的?我刚刚用这个,没用过go语言,大家平常怎么使用gohangout的?是使用守护进程脚本后台启动这种方式?有人有打印日志的需求吗?
我用gohangout可以打印日志输入文件,但文件没办法自动滚动,担心在线上跑时间久了日志文件过大.

**Comment by childe** [comment]
我这边是用logrotate来做的


 
---原始邮件---
发件人: "devNullgh"<notifications@github.com>
发送时间: 2019年5月9日(星期四) 晚上9:18
收件人: "childe/gohangout"<gohangout@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [childe/gohangout] 有输出日志按照天或者大小滚动的功能吗? (#30)



大家平常打印日志是怎么用的?我刚刚用这个,没用过go语言,大家平常怎么使用gohangout的?是使用守护进程脚本后台启动这种方式?有人有打印日志的需求吗?
 我用gohangout可以打印日志输入文件,但文件没办法自动滚动,担心在线上跑时间久了日志文件过大.

**Comment by devNullgh** [comment]
@childe
这个logrotate您已经集成到了gohangout了是吗？还是需要我自己写代码加入？

**Comment by zhoufwind** [comment]
@devNullgh logrotate是linux系统自带的，适用于大部分程序日志切分场景，创建logrotate配置文件就可以实现日志切分，与gohangout本身无强关联，可以网上搜下`logrotate.d`关键字，有很多文档可以参考。

**Comment by devNullgh** [comment]
@zhoufwind
谢谢，我去研究一下。还有个问题，因为公司里有写入clickhouse的需求，这个我看gohangout也是支持的，但假如说有一台clickhouse机器突然断电关机这类故障，gohangout能自己发现故障机然后跳过故障机的ip，只往其他正常机器上写入吗？如果还在往故障机上写的话那就会丢数据了

**Comment by childe** [comment]
@devNullgh 会往新的写.  PS 新的问题最好新开一个issue ~

**Comment by devNullgh** [comment]
@childe 
谢谢，因为是想顺带请教一下所以就没有另开，您这里刚刚说会往新的写是指某一台clickhouse机器挂掉以后，gohangout会检测出故障机IP，然后创建出新的不包含故障机的ip列表，只往这个clickhouse的新IP列表写入，不会丢失数据，是这个意思吗？没太看明白。。。

**Comment by childe** [comment]
clikchouse output里面配置多个host列表, 失败了尝试下一个.
