### ISSUE TITLE
请教一下gohangout启动时怎么开启多进程?

### ISSUE THREAD

**Issue by devNullgh** [childe/gohangout#31]
请教一下各位,我看readme里面--worker 是调用多个线程,消费kafka的input中weblog: 5 也只是开5个线程,如果想开启多个进程的话怎么操作?不是很懂这一块

**Comment by childe** [comment]
多进程的话就起多个实例.

--worker 5 是指5个线程去做Filter以及Output.

weblog: 5 不仅5个线程去做Filter以及Output. Input也是五个线程(其实还会有5个group consumer, 如果你不知道这个是什么, 可以忽略).  

因为Input从kafka消费数据的时候, 会有解压以及Json解码等工作, 如果这里有瓶颈, 可以使用 weblog: 5这种. 否则推荐上面那种.

**Comment by devNullgh** [comment]
@childe
起多个gohangout进程(每个进程还包括多个线程),会造成数据重复消费吗?
因为目前我这里的实际数据中会有部分重复,所以我无法验证:
(1)该数据是本身存在于kafka内就重复(正常情况)
(2)gohangout重复消费了未重复数据(异常情况)
我启动的每个进程的所有配置包括group.id都完全相同.
还有就是,kafka内是json数据,output到clickhouse的话,yml配置文件里clickhouse那一块的fields字段配置有什么要求吗?比如
(1)fields字段顺序必须对应kafka内key的顺序还是必须对应clickhouse表字段顺序?
(2)clickhouse表字段名是否必须和json数据的key大小写完全相同?

**Comment by childe** [comment]
gorupid一样, 不会重复消费.

clickhouse里面的fields就是说json里面的哪些字段到clickhouse, 一般来说clickhouse里面的表有哪些字段, 就配置哪些字段.
