### ISSUE TITLE
kafka有大量堆积用gohangout消费产生oom

### ISSUE THREAD

**Issue by anzerchen** [childe/gohangout#33]
kafka0.10.2,保存6小时的数据大概2T。后面两台16c32g机器只运行gohangout v1.2.4 单进程单线程用来消费kafka中日志数据，出现过多次高峰期lag逐渐增大后gohangout的oom现象

E0525 23:24:54.782056    2735 group_consumer.go:449] failed to send heartbeat: The group is rebalancing, so a rejoin is needed.
E0525 23:24:54.799387    2735 group_consumer.go:449] failed to send heartbeat: The group is rebalancing, so a rejoin is needed.
E0525 23:24:54.818359    2735 group_consumer.go:449] failed to send heartbeat: The group is rebalancing, so a rejoin is needed.
E0525 23:24:54.822726    2735 group_consumer.go:449] failed to send heartbeat: The group is rebalancing, so a rejoin is needed.
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x97528d, 0x16)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc770000000, 0x4000000, 0xdb3ad8)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0xd9a7c0, 0x4000000, 0x80, 0x0)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0xd9a7c0, 0x3b5, 0x0)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0xd9a7c0, 0x3b5, 0xdb3ae8, 0xc0001e9ed8)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0xd9a7c0, 0x3b5, 0xc000340101, 0x1000000001)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0xd9a7c0, 0x3b5, 0xc000010101, 0xc0fcfe7680)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x768c93, 0xc423a00101, 0xc76f2fe001)
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
        /usr/local/Cellar/go/2.11.2/libexec/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/proc.go:1229

goroutine 8502 [running]:
runtime.systemstack_switch()
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:311 fp=0xc11d703490 sp=0xc11d703488 pc=0x459900
runtime.mallocgc(0x768c93, 0x8a9c00, 0x5a01, 0xffff)

**Comment by childe** [comment]
1. 你是跑在容器里面吗? 如果是, 有内存限制吗?
2 系统内存多少, 禁用swap了吗?
3. 看下你的配置文件内容.

**Comment by anzerchen** [comment]
1.跑在阿里云ecs
2.禁用swap了
配置文件如下，input有多组kafka这里只取一组示例
inputs:
    - Kafka:
        codec: json
        topic:
          36level2-1: 1
          36level2-2: 1
          36level2-3: 1
          36level2-4: 1
          36level2-5: 1
          36level2-6: 1
          36level2-7: 1
          36level2-8: 1
          36level2-9: 1
          36level2-10: 1
        consumer_settings:
          group.id: 36level2
          bootstrap.servers: "x.x.x.x:9092,x.x.x.x:9092,x.x.x.x:9092"
filters:
    - Lowercase:
        fields: ['business']
    - Convert:
        fields:
          body_bytes_sent:
              to: int
          upstream_response_time:
              to: float
          request_time:
              to: float
          req_time:
              to: float
          elapsedMilliseconds:
              to: int
          val:
              to: int
    - Remove:
        fields: ['ResetTime', 'Queues', 'ret', 'offset', 'tags', 'beat', 'input_type']
    - Rename:
        fields:
          source: path
outputs:
    - Elasticsearch:
        hosts:
          - http://x.x.x.x:9200
          - http://x.x.x.x:9200
          - http://x.x.x.x:9200
          - http://x.x.x.x:9200
          - http://x.x.x.x:9200
          - http://x.x.x.x:9200
          - http://x.x.x.x:9200
          - http://x.x.x.x:9200
        index: '%{business}-%{+2006.01.02}'
        index_type: "span"
        bulk_actions: 50000
        bulk_size: 20
        flush_interval: 60
        compress: false

**Comment by anzerchen** [comment]
> 1. 你是跑在容器里面吗? 如果是, 有内存限制吗?
>    2 系统内存多少, 禁用swap了吗?
> 2. 看下你的配置文件内容.

1.跑在阿里云ecs
2.禁用swap了
配置文件如下，input有多组kafka这里只取一组示例
inputs:
- Kafka:
codec: json
topic:
36level2-1: 1
36level2-2: 1
36level2-3: 1
36level2-4: 1
36level2-5: 1
36level2-6: 1
36level2-7: 1
36level2-8: 1
36level2-9: 1
36level2-10: 1
consumer_settings:
group.id: 36level2
bootstrap.servers: "x.x.x.x:9092,x.x.x.x:9092,x.x.x.x:9092"
filters:
- Lowercase:
fields: ['business']
- Convert:
fields:
body_bytes_sent:
to: int
upstream_response_time:
to: float
request_time:
to: float
req_time:
to: float
elapsedMilliseconds:
to: int
val:
to: int
- Remove:
fields: ['ResetTime', 'Queues', 'ret', 'offset', 'tags', 'beat', 'input_type']
- Rename:
fields:
source: path
outputs:
- Elasticsearch:
hosts:
- http://x.x.x.x:9200
- http://x.x.x.x:9200
- http://x.x.x.x:9200
- http://x.x.x.x:9200
- http://x.x.x.x:9200
- http://x.x.x.x:9200
- http://x.x.x.x:9200
- http://x.x.x.x:9200
index: '%{business}-%{+2006.01.02}'
index_type: "span"
bulk_actions: 50000
bulk_size: 20
flush_interval: 60
compress: false

**Comment by childe** [comment]
如果你的内存小, 的确可以会OOM.
默认情况, 一个线程里面,  消费kafka可能会使用10M, 写ES会有40M.  36level2-1: 1  这样一个配置就是一个线程.  所以你这样配置下来, 需要的内存可能是非常非常大的.

**Comment by anzerchen** [comment]
> 如果你的内存小, 的确可以会OOM.
> 默认情况, 一个线程里面, 消费kafka可能会使用10M, 写ES会有40M. 36level2-1: 1 这样一个配置就是一个线程. 所以你这样配置下来, 需要的内存可能是非常非常大的.

我们kafka之前用的0.9.0.0版本，用相同配置还是多线程跑过几个月都没出现过oom，我想是不是跟kafka升级有一定关系。

**Comment by childe** [comment]
我暂时想不到升级0.9.0.0到0.10.2会有什么影响. 我的感觉是ES最近压力比较大, 导致一些内存中的数据不能释放被GC, 每个线程都会占住大概50M+内存, 导致最后OOM.
如果你们之前稳定运行的时候, 不会有数据堆积, 那就可以这么解释.  如果你们之前也是每个topic都有大量堆积却没有OOM, 可能是别的原因了.

**Comment by anzerchen** [comment]
> 我暂时想不到升级0.9.0.0到0.10.2会有什么影响. 我的感觉是ES最近压力比较大, 导致一些内存中的数据不能释放被GC, 每个线程都会占住大概50M+内存, 导致最后OOM.
> 如果你们之前稳定运行的时候, 不会有数据堆积, 那就可以这么解释. 如果你们之前也是每个topic都有大量堆积却没有OOM, 可能是别的原因了.

嗯，感谢回复，我自己再去查查。
