### ISSUE TITLE
output中bulk_actions bulk_size flush_interval的优先级

### ISSUE THREAD

**Issue by anzerchen** [childe/gohangout#34]
配置如下
单线程
bulk_actions: 100000
bulk_size: 200
flush_interval: 60
我测试下来发现有两种情况
1.kafka有堆积时 如果100000条不超过200m则满100000就往es发，如果不满100000条但达到200m则换算200m的对应条数往es发，并且此时flush_interval配置无效
I0528 15:18:44.059359   20568 bulk_http.go:156] bulk 100000 docs with execution_id 25
I0528 15:18:49.322766   20568 bulk_http.go:156] bulk 100000 docs with execution_id 26
I0528 15:18:54.482141   20568 bulk_http.go:156] bulk 100000 docs with execution_id 27
I0528 15:18:59.659397   20568 bulk_http.go:156] bulk 100000 docs with execution_id 28
I0528 15:19:04.777812   20568 bulk_http.go:156] bulk 100000 docs with execution_id 29
I0528 15:19:09.591249   20568 bulk_http.go:156] bulk 20574 docs with execution_id 30
I0528 15:19:10.649654   20568 bulk_http.go:156] bulk 100000 docs with execution_id 31
I0528 15:19:15.721720   20568 bulk_http.go:156] bulk 100000 docs with execution_id 32
I0528 15:19:21.540412   20568 bulk_http.go:156] bulk 100000 docs with execution_id 33
I0528 15:19:26.316815   20568 bulk_http.go:156] bulk 100000 docs with execution_id 34
I0528 15:19:31.515927   20568 bulk_http.go:156] bulk 100000 docs with execution_id 35
I0528 15:19:37.102144   20568 bulk_http.go:156] bulk 100000 docs with execution_id 36
I0528 15:19:42.326828   20568 bulk_http.go:156] bulk 100000 docs with execution_id 37
I0528 15:19:46.972345   20568 bulk_http.go:156] bulk 100000 docs with execution_id 38
I0528 15:19:51.771179   20568 bulk_http.go:156] bulk 100000 docs with execution_id 39

2.无堆积时，按正常flush_interval配置的周期换算数据量运行：
I0528 16:10:31.727049   28031 bulk_http.go:156] bulk 1516 docs with execution_id 106
I0528 16:11:31.711819   28031 bulk_http.go:156] bulk 1473 docs with execution_id 107
I0528 16:12:31.727624   28031 bulk_http.go:156] bulk 1508 docs with execution_id 108
I0528 16:13:31.726607   28031 bulk_http.go:156] bulk 1474 docs with execution_id 109
I0528 16:14:31.712247   28031 bulk_http.go:156] bulk 1497 docs with execution_id 110
I0528 16:15:31.714574   28031 bulk_http.go:156] bulk 1469 docs with execution_id 111
I0528 16:16:31.712348   28031 bulk_http.go:156] bulk 1506 docs with execution_id 112
I0528 16:17:31.712169   28031 bulk_http.go:156] bulk 1472 docs with execution_id 113
I0528 16:18:31.714599   28031 bulk_http.go:156] bulk 1499 docs with execution_id 114
I0528 16:19:31.728199   28031 bulk_http.go:156] bulk 1481 docs with execution_id 115
I0528 16:19:32.193729   28031 bulk_http.go:156] bulk 180 docs with execution_id 116
I0528 16:20:31.711735   28031 bulk_http.go:156] bulk 1511 docs with execution_id 117
I0528 16:21:31.730355   28031 bulk_http.go:156] bulk 1468 docs with execution_id 118
I0528 16:22:31.725153   28031 bulk_http.go:156] bulk 1520 docs with execution_id 119
I0528 16:23:31.712136   28031 bulk_http.go:156] bulk 1465 docs with execution_id 120
I0528 16:24:31.715234   28031 bulk_http.go:156] bulk 1513 docs with execution_id 121
I0528 16:25:31.711754   28031 bulk_http.go:156] bulk 1459 docs with execution_id 122
I0528 16:26:31.712235   28031 bulk_http.go:156] bulk 1510 docs with execution_id 123
I0528 16:27:31.712951   28031 bulk_http.go:156] bulk 1476 docs with execution_id 124
I0528 16:28:31.727973   28031 bulk_http.go:156] bulk 1481 docs with execution_id 125
I0528 16:29:31.711916   28031 bulk_http.go:156] bulk 1521 docs with execution_id 126
I0528 16:30:31.713283   28031 bulk_http.go:156] bulk 1480 docs with execution_id 127

是否是这种机制呢？

**Comment by childe** [comment]
bulk_actions 和 bulk_size 没有优化级, 哪个条件到了都会触发写ES.
flush_interval 是定期刷, 不管上面两个条件是否满足都会写ES.  你上面的 `I0528 15:19:09.591249 20568 bulk_http.go:156] bulk 20574 docs with execution_id 30` 应该就对应这个.
