### ISSUE TITLE
关于写入es索引时间问题

### ISSUE THREAD

**Issue by hiflycat** [childe/gohangout#35]
写入es，创建索引晚了8个小时，请问在哪里配置时区？

**Comment by childe** [comment]
https://github.com/childe/gohangout/blob/master/example.yml#L31

**Comment by hiflycat** [comment]
<img width="1087" alt="图片" src="https://user-images.githubusercontent.com/25202901/59203317-e8ff1380-8bd0-11e9-8f34-36c146b781b3.png">
我是这样配置的，好像不行

**Comment by childe** [comment]
我可能误解你的意思了.
你是说北京时间早晨8点创建索引?  这个是从 logstash 年代一直以为约定俗成的, 而且这个和 Kibana(至少是 Kibana3)配合工作的. 如果在北京时间0点创建索引, 会导致0点-8点数据在 kibana 上面搜索不到, 至少 kibana3 是这样.
目前代码中还没有实现看 UTC 时区来生成索引名字, 有需求的话后面可以考虑添加.

**Comment by dockersky** [comment]
现在是没有办法按照Asia/Shanghai，本地时间去创建索引吗？

**Comment by childe** [comment]
@dockersky 嗯, 是的, 一直还没有加这个功能. 加好了通知你.

**Comment by dockersky** [comment]
刚刚改了你的代码，已经实现了。有需要的可以参考一下


![image](https://user-images.githubusercontent.com/20313381/67474869-b9384000-f687-11e9-9401-2ec2dc8085e4.png)

**Comment by childe** [comment]
@dockersky 好的, 多谢. 建议把 glog.info  去掉, 否则太多日志了.

**Comment by childe** [comment]
@hiflycat @dockersky 实现推到 Dev 分支了. 可以参考  https://github.com/childe/gohangout/tree/584b94a

配置一下 index_time_location

**Comment by dockersky** [comment]
@childe 太好了，方便加个微信吗？

**Comment by dockersky** [comment]
@childe 太好了，方便加个微信吗？


![2](https://user-images.githubusercontent.com/20313381/67546090-ed663c00-f72d-11e9-8a01-705290b58b84.png)
