### ISSUE TITLE
ipip字段类型不符

### ISSUE THREAD

**Issue by devNullgh** [childe/gohangout#40]
报错日志:
error: location (String): unexpected type map[string]interface {}

我的过滤器设置为:
     - IPIP:
          src: ip
          target: location
          database: /opt/gohangout/ipdata.datx

gohangout的target字段类型必须是interface吗?我将location设置成String想要直接写入到ch中应该如何设置呢?ch的字段里已经设置了location

**Comment by childe** [comment]
不要设置 Target, 然后你用 Stdout 输出看一下增加的几个地理位置字段. 应该能看明白怎么配置 CH 里面的字段.

**Comment by devNullgh** [comment]
@childe 
我进行了std输出,输出结果为json嵌套json,即
`{"serverIp":"1.2.3.4","geoip":{"country_name":"中国","province_name":"河南","city_name":"郑州"},"clientIp":"2.3.4.5"}`
这种json套json的形式,我的想法是对serverIp定位,比如这里输出geoip,然后将country_name更改为server_country,并入库到ch的对应server_country字段,省份与城市依次类推,clientIp也照此处理,gohangout可以解析这种json套json的形式吗?我尝试使用了filter-json,格式:
`    - Json:
          field: country_name
          target: server_country`
或者
`    - Json:
          field: geoip
          target: server_country,server_province,server_city`
或者
`    - Json:
          field: geoip`
这三种格式都不能解析json,对go了解不深,看了说明依然没搞清楚格式.

**Comment by devNullgh** [comment]
@childe 
我对你之前的话不是很理解,即便我在ch中新增了名为geoip的字段,入ch时依然会报出库中geoip的类型String与map[string]interface不匹配

**Comment by childe** [comment]
@devNullgh 抱歉, 我说错了, 应该这样写

```
- IPIP:
src: ip
target: ''
database: /opt/gohangout/ipdata.datx
```
