### ISSUE TITLE
目前java和go版本的hangout分别支持到什么版本的kafka和es?

### ISSUE THREAD

**Issue by lannyMa** [childe/gohangout#43]
1.是否支持 es7.1?
2.是否支持最新版本的kafka的SASL_PLAINTEXT 认证方式

filebeat: Only SASL/PLAIN is supported
https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html

但是 logstash支持:string, one of ["PLAINTEXT", "SSL", "SASL_PLAINTEXT", "SASL_SSL"]
https://www.elastic.co/guide/en/logstash/6.6/plugins-outputs-kafka.html

hangout只支持kafka的plain加密方式吗?
![image](https://user-images.githubusercontent.com/16549395/60695404-2f1b6e80-9f14-11e9-9d9c-ec0ed1da6e8a.png)

**Comment by childe** [comment]
1. 有可能不支持吧. 我还没测过. 你可以试下看.
2. hangout应该支持, 因为就是使用的官方的 Client.  Gohangout 目前支持 ["PLAINTEXT", "SSL", "SASL_PLAINTEXT", "SASL_SSL"] , 但是 SASL 里面的认证方式还只是支持 PLAIN.  (你需要知道这几个 PLAIN 的区别.. )

**Comment by zhoufwind** [comment]
1. 我这边测试过es 7.3.0，gohangout可正常运行。

**Comment by shengfanzuo** [comment]
>     1. 我这边测试过es 7.3.0，gohangout可正常运行。
我这里测试了 7.3.1 版本的ES，gohangout和hangout 能创建索引，但是健康状态是red，没有找到原因，不确定是否跟 index_type 指令有关，7XX版本的ES已经没有索引type了，不知道你这边是如何配置的？

**Comment by childe** [comment]
@shengfanzuo 
你先看一下什么是 Red, 为什么 Shard 不能分配. 我觉得不是 Type 原因, 因为Type 不正确根本不会创建出来索引.

**Comment by shengfanzuo** [comment]
> @shengfanzuo
> 你先看一下什么是 Red, 为什么 Shard 不能分配. 我觉得不是 Type 原因, 因为Type 不正确根本不会创建出来索引.

1、hangout和gohangout都能用http的方式创建索引，用9300端口的话无法连接cluster
![图片](https://user-images.githubusercontent.com/47919055/63997758-038ebc00-cb32-11e9-9e55-80c81dffd9aa.png)

2、hangout报错
![图片](https://user-images.githubusercontent.com/47919055/63998396-92e89f00-cb33-11e9-9437-6881de563cb2.png)

3、gohangou报错
![图片](https://user-images.githubusercontent.com/47919055/63998654-2ae68880-cb34-11e9-9800-cff18ad49b78.png)

4、7.3.1 ES集群的日志
![图片](https://user-images.githubusercontent.com/47919055/63998855-b3652900-cb34-11e9-94f0-7bd70d84face.png)

    我这里能找到的信息就是这些了，分片看起来都是有的，hangout的数据直接写到hangout输出日志中了，不确定具体问题在哪里，所以迫切想知道 @zhoufwind 是咋配置的gohangout的output的

**Comment by childe** [comment]
@shengfanzuo 这个应该和配置没关系, 你要看为什么索引是红的. https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html
