### ISSUE TITLE
Filter Json 写法是如何的？

### ISSUE THREAD

**Issue by chijiajian** [childe/gohangout#47]
filters:
    - Json:
        field: '[log]'
        target: '[k8s][log]'

还是
filters:
    - Json:
        field: 'log'
        target: 'k8s'

**Comment by childe** [comment]
给一个具体的例子?  说一下你的原数据, 以及你想处理成什么样子.

**Comment by chijiajian** [comment]
> 给一个具体的例子? 说一下你的原数据, 以及你想处理成什么样子.

谢谢，我是想处理多层嵌套，解析出1层json写入CH, 一开始我用filters:  -Json来搞的，一直没有搞定。
我现在用以下方式可以处理，不知道是否为最佳方式
filters:
    - Add:
        fields:
            B: '[A][B]'
然后再remove_fields: 掉上一层的JSON。

**Comment by childe** [comment]
目前只能是这样～


 
---原始邮件---
发件人: "chijiajian"<notifications@github.com>
发送时间: 2019年7月25日(星期四) 下午5:06
收件人: "childe/gohangout"<gohangout@noreply.github.com>;
抄送: "childe"<rmself@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [childe/gohangout] Filter Json 写法是如何的？ (#47)


 
给一个具体的例子? 说一下你的原数据, 以及你想处理成什么样子.
  
谢谢，我是想处理多层嵌套，解析出1层json写入CH, 一开始我用filters:  -Json来搞的，一直没有搞定。
 我现在用以下方式可以处理，不知道是否为最佳方式
 filters:
 - Add:
 fields:
 B: '[A][B]'
 然后再remove_fields: 掉上一层的JSON。
