### ISSUE TITLE
考虑支持下LowCardinality(String)？

### ISSUE THREAD

**Issue by liaoxu** [childe/gohangout#49]
https://www.altinity.com/blog/2019/3/27/low-cardinality

是否考虑支持下这个类型呢？clickhouse 最新版已经可以使用了

**Comment by childe** [comment]
最近可能没时间搞, 每天加班到好晚.. 
不过我的感觉是, 这个建表的时候定义成 LowCardinality 不行? 还需要写入的时候额外处理?

**Comment by liaoxu** [comment]
> 最近可能没时间搞, 每天加班到好晚..
> 不过我的感觉是, 这个建表的时候定义成 LowCardinality 不行? 还需要写入的时候额外处理?

就是建表时用LowCardinality(String) 代替 String，具体这个代码，clickhouse_output.go里面因为没有“LowCardinality(String)”这个类型索引检查会报错“unsupported column type, ignore”，加入和 string 相同的 case 应该就行了

**Comment by childe** [comment]
多谢你的建议! 估计要忙完这几天, 想改成 SQL + HTTP 的形式, 会灵活一些吧, 不受第三方库的限制了
