### ISSUE TITLE
有考虑添加消费kafka解析avro类型数据的功能吗?

### ISSUE THREAD

**Issue by devNullgh** [childe/gohangout#51]
avro以及类似的比如Zstandard一类的,lz4的实现好像有些问题,会显示解压失败,gzip解压效率感觉很低,目前在用snappy.

**Comment by childe** [comment]
之前尝试过 Avro, 用的第三方的库, 好像是 Facebook 的. 但我们公司 Java 编码后的数据, 解析失败, 简单的可以, 但复杂的不行. 还没有深入去查原因.

**Comment by childe** [comment]
LZ4的问题, 我在 https://github.com/childe/gohangout/issues/15 提到过. 根源是Kafka Java Client自己对 Lz4 编码的时候有问题, 导致别的库没法解码. 可以对 Go 的 Lz4的库的源码做修改后支持.

**Comment by childe** [comment]
lz4已经支持
