### ISSUE TITLE
kafka一条数据生成多条clickhouse数据的功能，现在能支持吗

### ISSUE THREAD

**Issue by taiyang-li** [childe/gohangout#53]
输入kafka msg格式： {"a": 1, "b": {1, 2, 3}, "c": 4}
要求输入到clickhouse生成三条数据，分别是
{"a": 1, "b": 1, "c": 4}
{"a": 1, "b": 2, "c": 4}
{"a": 1, "b": 3, "c": 4} 
请问这样的需求现在能支持吗

**Comment by childe** [comment]
不支持, 这个得需要码代码实现新的功能才行.
