### ISSUE TITLE
如何把这个日期时间（带毫秒）字串转成数字？

### ISSUE THREAD

**Issue by henryleecn** [childe/gohangout#54]
由于ClickHouse的DateTime的精度不支持毫秒，在kafka消息中的json内容中有一个日期时间字段，如何把这个日期时间字段转成Uint64保存到ClickHouse？
json格式如：
{"createAt": "2019-08-12 21:39:22.795" ...}

**Comment by childe** [comment]
没听说过还有这个问题, 使用 Date 先转成 Date 类型呢.

```
- Date:
    formats:
    - '2016-01-02 15:04:05.000'
    src: createAt
    target: createAt
```

如果还不行, 那就使用 Grok 把不带毫秒的前半部分提取出来.

**Comment by henryleecn** [comment]
感谢@childe的回复。我们的场景是这样的：采集网关（硬件设备，它是标准的量产产品，不能修改数据格式）从终端设备采集数据，采集网关把数据推送到kafka，然后用gohangout从kafka同步到ClickHouse。网关推送到kafka的数据是json格式，数据内容类似 {"createAt": "2019-08-12 21:39:22.795", "count":16, "kio":0, "mio":1}，现在遇到的问题是ClickHouse的DateTime的精度不支持毫秒，把createAt转成DateTime类型后丢失了毫秒。在业务中是需要计算不同消息的时间差（单位是毫秒）。所以才提出这个问题。如果ClickHouse的DateTime的精度能支持毫秒就没有这个问题了。又不想因为这个问题放弃使用gohangout，麻烦@childe帮忙想想办法

**Comment by childe** [comment]
所以是想把时间转成 Unit64 存到 Clickhouse 里面, Clickhouse 里面也不使用 DateTime 类型, 而是使用Uint64? 我现在只能想到一个毕竟笨的办法

```
filters:
    - Date:
        src: message
        target: t
        location: 'Asia/Shanghai'
        formats:
        - '2006-01-02 15:04:05.000'
        add_fields:
            a: '{{divide .t.UnixNano 1000000}}'

    - Convert:
        fields:
            a:
                to: int
```

**Comment by henryleecn** [comment]
@zhoufwind ,按照你给的转换，计算出的结果是0
配置如下：
`
filters:
    - Date:
        src: 'createDate'
        location: Asia/Shanghai
        add_year: false
        formats:
            - '2006-01-02 15:04:05.000'
        add_fields:
            createAt: '{{divide.t.UnixNano 1000000}}'
    - Convert:
        fields:
            createAt:
                to: int
`

**Comment by childe** [comment]
应该是下面这样

```
    - Date:
        src: 'createAt'
        target: t
        location: Asia/Shanghai
        add_year: false
        formats:
            - '2006-01-02 15:04:05.000'
        add_fields:
            temp: '{{divide .t.UnixNano 1000000}}'
    - Convert:
        fields:
            temp:
                to: int
```

**Comment by henryleecn** [comment]
@childe ,  在类型转换时出错了。
表结构：
‘’‘
CREATE TABLE order3 (
    id UInt64,
    type String,
    createAt UInt64
) ENGINE = MergeTree() ORDER BY (id);
’‘’

gohangout配置：
'''
inputs:
    - Kafka:
        topic:
            dev01: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "kafka_kafka_1:9092"
            group.id: gohangout.goweblog
filters:
    - Date:
        src: 'createDate'
        target: t
        location: Asia/Shanghai
        add_year: false
        formats:
            - '2006-01-02 15:04:05.000'
        add_fields:
            createAt: '{{divide .t.UnixNano 1000000}}'
    - Convert:
        fields:
            id:
                setto_if_fail: 0
                to: int
            createAt:
                to: int
outputs:
    - Clickhouse:
        table: 'default.devices'
        hosts:
            - 'tcp://clickhouse-server:9000'
        fields: ['id', 'type', 'createAt']
        bulk_actions: 10
        flush_interval: 30
        concurrent: 1
'''

出错日志：
‘’‘
E0825 01:42:05.942189     236 clickhouse_output.go:339] exec clickhouse insert map[@timestamp:2019-08-25 01:41:56.8396782 +0000 UTC m=+38.591737001 type:E id:1566697316778 createDate:2019-08-25 09:41:56.782 t:2019-08-25 01:41:56.782 +0000 UTC createAt:1566697316782] error: createAt (UInt64): unexpected type string
’‘’

**Comment by childe** [comment]
@henryleecn strconv.ParseInt的时候给的精度不够, 导致转换失败了.

8038155065c28357ed025c53959468cfb56fef2a 已经修复, 你自己 Make 一下?

**Comment by henryleecn** [comment]
非常感谢 @childe ，占用了你的休息时间。因为go语言没有玩过，如果你方便的话在你空闲的时候帮我Make一个linux-x64文件，感谢！！

**Comment by childe** [comment]
[gohangout-linux-x64-8038155.zip](https://github.com/childe/gohangout/files/3539211/gohangout-linux-x64-8038155.zip)

**Comment by henryleecn** [comment]
@childe , 验证OK！非常感谢！！！
