### ISSUE TITLE
 增加字段没识别

### ISSUE THREAD

**Issue by 838279033** [childe/gohangout#60]
inputs:
    - Kafka:
        topic:
            clog_six: 20
        codec: json
        consumer_settings:
            bootstrap.servers: xl.kafka8.com:6667,xl.kafka9.com:6667,xl.kafka10.com:6667
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group.id: gnuhpscssssssda
Add:
  overwrite: true
  fields:
      aa: '[pkg][productID]'
outputs:
    - Clickhouse:
         hosts:
             - 'tcp://192.168.2.93:9000'
         table: 'default.t66'
         fields: ['aa']

kafka中的数据是{
	"data": {
		"source": "iqiyi",
		"forum_id": "10132",
		"block_name": "",
		"mainpage_version": "7090064",
		"is_user_vip": "闈濾IP",
		"mainpage_type": "Common",
		"forum_name": "杞挱鍒楄〃",
		"page_name": "涓婚〉",
		"A_or_B": "A",
		"_occurrence_time": "43865",
		"forum_pid": "0",
		"block_id": "10101"
	},
	"device": {
		"address": "",
		"jscn_ca": "",
		"os_vercode": 18011300,
		"brand": "SKYWORTH",
		"barcode": "55G7XXX-R107471-H170108-48EA3",
		"os_vername": "6.20.181130",
		"deviceSN": "",
		"sfmode": "Default",
		"home_ver": 7090064,
		"chip": "9R59",
		"model": "G7"
	},
	"did": "71937482",
	"ip": "183.225.64.174",
	"logid": "a75f5955d8b12b162e20f0374065f8e4",
	"mac": "60427f7d5ed8",
	"name": "broadcast_show",
	"pkg": {
		"pkg_vercode": 7090064,
		"pkg_source": "yinhe",
		"productID": "CC_HomePage6",
		"pkg_name": "com.tianci.movieplatform",
		"pkg_vername": "7.9.64"
	},
	"rtime": "1570869799672",
	"sid": "05e45bb1-91ce-4a0c-9d07-072ea36b8085",
	"time": "43865",
	"uid": "be715a7026b311e8ac64525400f3186f"
}

aa: '[pkg][productID]' 中拿到的数据是空的，问题是出在哪里了呢

**Comment by 838279033** [comment]
已解决

**Comment by childe** [comment]
请问是怎么回事啊?
