### ISSUE TITLE
怎么将kafka的数据消费到http中

### ISSUE THREAD

**Issue by lovrainy** [childe/gohangout#67]
怎么将kafka的数据消费到http中，也就是output为http

**Comment by childe** [comment]
还没有单独的 HTTP OUTPUT

**Comment by lovrainy** [comment]
output中 buld_http是用来做http output的吗

**Comment by lovrainy** [comment]
> 还没有单独的 HTTP OUTPUT

output中 buld_http能用来做http output吗

**Comment by childe** [comment]
> > 还没有单独的 HTTP OUTPUT
> 
> output中 buld_http能用来做http output吗

不能直接用
