### ISSUE TITLE
配置文件是否支持动态刷新和加载

### ISSUE THREAD

**Issue by linjikun** [childe/gohangout#68]
修改配置的yml文件是否需要重启

**Comment by childe** [comment]
嗯, 现在是这样的

**Comment by linjikun** [comment]
如果自己扩展动态加载配置文件，会很难么

**Comment by childe** [comment]
> 如果自己扩展动态加载配置文件，会很难么

想一想好像也不是很难 , 就是要处理好 input/output 的 shutdown .  比如把当前已经读出来的数据写到 ES里面, 把当前的 Offset Commit 到 Kafka

**Comment by linjikun** [comment]
感谢，按你的说法，应该可以操作

**Comment by linjikun** [comment]
请问支不支持同时加载多个配置文件

**Comment by childe** [comment]
> 请问支不支持同时加载多个配置文件

不支持, 可以使用 Yaml 自己的 include  机制. 但也不能多个文件一起.  参考下 https://github.com/childe/hangout/issues/99
