### ISSUE TITLE
最新版 gohangout 开 180个实例消费180个分区，启动和任何一个实例加入退出都会卡一小会 The group is rebalancing，logstash 没这个问题就是消耗资源太多

### ISSUE THREAD

**Issue by childe** [childe/gohangout#69]
最新版 gohangout 开 180个实例消费180个分区，启动和任何一个实例加入退出都会卡一小会 The group is rebalancing，logstash 没这个问题就是消耗资源太多

_Originally posted by @zcola in https://github.com/childe/gohangout/issues/38#issuecomment-561057073_

**Comment by childe** [comment]
按我对 Kafka 协议的了解, Logstash 应该也会 rebalance.

**Comment by zcola** [comment]
> 按我对 Kafka 协议的了解, Logstash 应该也会 rebalance.

有什么下文吗？中间楼层怎么不见了奇怪

**Comment by childe** [comment]
没有中间楼层, 你可能是说的 https://github.com/childe/gohangout/issues/70#event-2899434318 这个 Issue 吧.
