### ISSUE TITLE
kafka的input可以支持一下指定partition消费么？

### ISSUE THREAD

**Issue by jasper-zhang** [childe/gohangout#7]

**Comment by childe** [comment]
张总的需求一定尽量满足.

**Comment by jasper-zhang** [comment]
谢谢佳爷 👍

**Comment by childe** [comment]
c65619663e17788695a04b9e72d46a7aa7b36cef 添加了这个功能. 先要 pull 一下  github.com/childe/healer

**Comment by jasper-zhang** [comment]
亲测可用，不过 `kafka_input` 里面少了个fromBeginning参数，我自己加上了

**Comment by childe** [comment]
from.beginning 参数添加了. 
github.com/childe/healer 也做了相应的改动, 需要pull. 
之前的 consumer.Consume(fromBeginning) 这里的 fromBeginning 参数去掉了, 因为这个配置已经在 consumer config 里面有了, 调用 Consume 的时候再传一个参数会让人迷惑.
