### ISSUE TITLE
grok支持多行（换行）

### ISSUE THREAD

**Issue by ever4Keny** [childe/gohangout#77]
大佬，我又来啦。遇到一个问题。例如，我用gohangout处理日志，日志里面经常有多行的情况，比如包含异常信息的错误日志，那我需要grok支持多行文本。不过我这边发现貌似gohangout不支持：
简单的一个例子，grok模板如下：
> %{TIMESTAMP_ISO8601:datetime}\s+%{GREEDYDATA:message}

这种情况下，遇到多行的日志，gohangout会只读取了第一行，后面的数据被扔掉了。而logstash可以支持。
怀疑是不是底层用的正则表达式的多行flag没有打开？麻烦大佬帮忙看看哈

**Comment by KrisOtk** [comment]
GREEDYDATA 本质上是 .* 不支持换行符的 需要自己改成相应的正则表达式

**Comment by KrisOtk** [comment]
(.|\r|\n)*)

**Comment by ever4Keny** [comment]
> GREEDYDATA 本质上是 .* 不支持换行符的 需要自己改成相应的正则表达式

好的 多谢 我试试

**Comment by childe** [comment]
@ever4Keny @KrisOtk 
谢谢帮忙回复. 

是这样的, 每种语言有自己的语法, Go 的可以看官方文档 https://github.com/google/re2/wiki/Syntax

在 Flag 这里, 你可以看到 

m | multi-line mode: ^ and $ match begin/end line in addition to begin/end text (default false)
-- | --
s | let . match \n (default false)


加上这两个 Flag, 可以实现你的需求.

@KrisOtk 按我的理解, 如果不加 m ,  即使 `(.|\r|\n)*)` 也不行.

**Comment by ever4Keny** [comment]
> @ever4Keny @KrisOtk
> 谢谢帮忙回复.
> 
> 是这样的, 每种语言有自己的语法, Go 的可以看官方文档 https://github.com/google/re2/wiki/Syntax
> 
> 在 Flag 这里, 你可以看到
> 
> m	multi-line mode: ^ and $ match begin/end line in addition to begin/end text (default false)
> s	let . match \n (default false)
> 加上这两个 Flag, 可以实现你的需求. 你在正则最前面写 (?ms) 再试下看吧
> 
> @KrisOtk 按我的理解, 如果不加 m , 即使 `(.|\r|\n)*)` 也不行.

多谢大佬！！
不过我尝试了一下 @KrisOtk 的解决方案，即使没有开m， (.|\r|\n)*这个是可行的！

**Comment by childe** [comment]
> 不过我尝试了一下 @KrisOtk 的解决方案，即使没有开m， (.|\r|\n)*这个是可行的！

@ever4Keny @KrisOtk 是我没搞清楚. 如果你最后写了 $ 这个锚点, 就得用 m 这个 Flag 了, 没写 $ 的话, 就不影响了.
