### ISSUE TITLE
建议升级clickhouse-go驱动

### ISSUE THREAD

**Issue by Dudiao137** [childe/gohangout#79]
在clickhouse-go驱动的1.3.4版本中，向clickhouse插入date类型的数值时，到clickhouse中会变成utc时区，导致8点前的数据会变成前一天的。后面的版本已经修复了这个问题。建议升级clickhouse-go的版本。

**Comment by Dudiao137** [comment]
https://github.com/ClickHouse/clickhouse-go/commit/e0b2c923879e8403f4221e833725dea5d4f7fcaa

**Comment by childe** [comment]
创建了一个发布 https://github.com/childe/gohangout/releases/tag/v1.4.2
