### ISSUE TITLE
Group authorization failed

### ISSUE THREAD

**Issue by guobinchn** [childe/gohangout#8]
你好，配置完成后启动服务，日志提示大量的错误信息，
I0103 17:52:37.389993  141941 group_consumer.go:190] join nginx.log error: Not authorized to access group: Group authorization failed.
I0103 17:52:37.490052  141941 group_consumer.go:167] try to join group nginx.log
I0103 17:52:37.490217  141941 group_consumer.go:190] join nginx.log error: Not authorized to access group: Group authorization failed.
I0103 17:52:37.590276  141941 group_consumer.go:167] try to join group nginx.log
I0103 17:52:37.590438  141941 group_consumer.go:190] join nginx.log error: Not authorized to access group: Group authorization failed.

版本为：v.0.0.1，  kafka为：1.0   配置如下：
inputs:
    - Kafka:
        topic:
            nginxlog: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "10.10.1.10:9092"
            group.id:  nginx.log
            client.id: nginxlog-aOwrp

**Comment by childe** [comment]
还不支持  :(
你们的kafka应该是配置了ACL了. 使用的自己写的kafka库, 还没有支持ACL. 我会尽快完善这个功能.

**Comment by guobinchn** [comment]
我们的kakfa是启用了acl，希望你尽快完成，加油！！！

**Comment by guobinchn** [comment]
非常感谢，我测试一下，另外方便留个联系方式吗，方便沟通。

**Comment by guobinchn** [comment]
我编译未能通过，方便生成一个二进制的吗?
