### ISSUE TITLE
centos7下运行，由于kafka版本为0.10导致无法拉取数据

### ISSUE THREAD

**Issue by zhousPole** [childe/gohangout#80]

**Comment by childe** [comment]
--logtostderr  --config XX.yaml  加前面这个参数, 看一下呢, 默认是打印到临时文件夹的文件里面的

**Comment by zhousPole** [comment]
> --logtostderr

![image](https://user-images.githubusercontent.com/38309664/78251301-b9d0de80-7523-11ea-9799-cbf3d3ce987b.png)
报错了

**Comment by childe** [comment]
--logtostderr -v 10 --config XX.yaml  打印详细的日志看一下呢

**Comment by childe** [comment]
你的 Kafka 是哪一个版本的?

**Comment by zhousPole** [comment]
> 你的 Kafka 是哪一个版本的?
0.10版本
![image](https://user-images.githubusercontent.com/38309664/78421407-f0286e00-7689-11ea-89d8-81532dd52ba6.png)

**Comment by zhousPole** [comment]
> 你的 Kafka 是哪一个版本的?

kafka应该是没问题的，我在控制台查看offset都是可以的
![image](https://user-images.githubusercontent.com/38309664/78421436-354ca000-768a-11ea-8b33-d7a40eed4cea.png)

**Comment by childe** [comment]
@zhousPole 这个真抱歉,  我一时看不出来问题在哪里. 看日志是超时了, 但为啥Join 会超时, 想不出来, 以前也没有碰到过.

你在 Kafka Server 上面能看到啥信息吗? 在 192.168.30.63 这个机器上.

**Comment by zhousPole** [comment]
> @zhousPole 这个真抱歉, 我一时看不出来问题在哪里. 看日志是超时了, 但为啥Join 会超时, 想不出来, 以前也没有碰到过.
> 
> 你在 Kafka Server 上面能看到啥信息吗? 在 192.168.30.63 这个机器上.

Kafka Server上面没有啥错误信息，和操作系统和kafka版本有关系么，操作系统是centos7

**Comment by idelin** [comment]
一模一样的问题，错误都一样

**Comment by childe** [comment]
是你们用的 Kafka 版本不支持新的 Join API, 我先使用老的 Join API编译 一个出来. 后面系统的更改代码处理这个问题.  @zhousPole @idelin 
[gohangout.zip](https://github.com/childe/gohangout/files/4442317/gohangout.zip)

**Comment by childe** [comment]
[gohangout.zip](https://github.com/childe/gohangout/files/4442387/gohangout.zip)
