### ISSUE TITLE
Kafka 故障恢复后不能恢复消费，刷报错，重启后从最新开始读

### ISSUE THREAD

**Issue by zcola** [childe/gohangout#82]
hangout 版本  1.3.1 kafka 0.10

kafka 故障后，hangout 报错
```
I0418 01:33:27.948472       1 bulk_http.go:144] bulk 15457 docs with execution_id 45326
I0418 01:33:27.948537       1 bulk_http.go:154] try to bulk with host (http://10.191.68.23:9200/_bulk)
I0418 01:33:28.980086       1 bulk_http.go:161] bulk done with execution_id 45326 1.032 15457 14977.712
I0418 01:37:27.950759       1 brokers.go:131] got 25 brokers
E0418 01:37:29.849768       1 simple_consumer.go:371] fetch error:read tcp 10.191.66.203:43008->10.191.54.224:9092: i/o timeout
E0418 01:37:29.849808       1 fetch_response.go:284] could not read enough bytes(4) to get fetchresponse length. read 0 bytes
I0418 01:37:29.949877       1 broker.go:177] broker  se.net:9092 is dead, (re)open it after sleep 200ms
E0418 01:38:00.651407       1 simple_consumer.go:371] fetch error:read tcp 10.191.66.203:48402->10.191.54.224:9092: i/o timeout
E0418 01:38:00.651467       1 fetch_response.go:284] could not read enough bytes(4) to get fetchresponse length. read 0 bytes
I0418 01:38:00.751551       1 broker.go:177] broker nease.net:9092 is dead, (re)open it after sleep 200ms
E0418 01:38:31.452661       1 simple_consumer.go:371] fetch error:read tcp 10.191.66.203:48446->10.191.54.224:9092: i/o timeout
E0418 01:38:31.452716       1 fetch_response.go:284] could not read enough bytes(4) to get fetchresponse length. read 0 bytes
I0418 01:38:31.552793       1 broker.go:177] broker .net:9092 is dead, (re)open it after sleep 200ms
E0418 01:39:02.285946       1 simple_consumer.go:371] fetch error:read tcp 10.191.66.203:48506->10.191.54.224:9092: i/o timeout
E0418 01:39:02.285993       1 fetch_response.go:284] could not read enough bytes(4) to get fetchresponse length. read 0 bytes
I0418 01:39:02.386042       1 broker.go:177] broker ease.net:9092 is dead, (re)open it after sleep 200ms
E0418 01:39:33.138383       1 simple_consumer.go:371] fetch error:read tcp 10.191.66.203:48588->10.191.54.224:9092: i/o timeout
E0418 01:39:33.138415       1 fetch_response.go:284] could not read enough bytes(4) to get fetchresponse length. read 0 bytes
I0418 01:39:33.238536       1 broker.go:177] broker i.nease.net:9092 is dead, (re)open it after sleep 200ms
E0418 01:40:03.945554       1 simple_consumer.go:371] fetch error:read tcp 10.191.66.203:48686->10.191.54.224:9092: i/o timeout
E0418 01:40:03.945592       1 fetch_response.go:284] could not read enough bytes(4) to get fetchresponse length. read 0 bytes
I0418 01:40:04.045787       1 broker.go:177] broker .i.nease.net:9092 is dead, (re)open it after sleep 200ms
省略重复
E0418 04:37:00.279222       1 brokers.go:269] get metadata of [suez_g66_logtail] from canal-sssez.i.nease.net:9092 error: There is no leader for this topic-partition as we are in the middle of a leadership election.
E0418 04:37:00.323861       1 brokers.go:269] get metadata of [suez_g66_logtail] from canal-kafssssase.net:9092 error: There is no leader for this topic-partition as we are in the middle of a leadership election.
E0418 04:37:00.387194       1 brokers.go:269] get metadata of [suez_g66_logtail] from canal-sss9-sssease.net:9092 error: There is no leader for this topic-partition as we are in the middle of a leadership election.
省略重复
E0418 06:28:36.474490       1 brokers.go:269] get metadata of [suez_g66_logtail] from canal-kafka14-suez.i.nease.net:9092 error: There is no leader for this topic-partition as we are in the middle of a leadership election.
E0418 06:28:36.675459       1 brokers.go:269] get metadata of [suez_g66_logtail] from canal-kafka10-suez.i.nease.net:9092 error: There is no leader for this topic-partition as we are in the middle of a leadership election.
kafka 故障恢复后，hangout 一直不消费，刷这个，强制重启后开始消费
I0418 06:28:36.876990       1 group_consumer.go:235] sync logstash_g66_logtail_11 error: The coordinator is not aware of this member.
I0418 06:28:36.877011       1 group_consumer.go:169] try to join group logstash_g66_logtail_11
I0418 06:28:36.877333       1 group_consumer.go:190] join logstash_g66_logtail_11 error: The coordinator is not aware of this member.
省略重复
I0419 00:00:00.001397       1 group_consumer.go:190] join logstash_g66_logtail_11 error: The coordinator is not aware of this member.
I0419 00:00:00.001403       1 group_consumer.go:169] try to join group logstash_g66_logtail_11
```

补充下时间点，kafka 是18日凌晨1点30全挂了，早上8点恢复，但是这个不消费是 19日22点发现并重启的，数据分区没有rotate，但是从最新读了，而且后面补数据重新指定offset 是可以消费的。

**Comment by childe** [comment]
@zcola 先看一下没有从 Offset 消费的问题. 有没有新启动后的数据的日志, 里面应该有取 Offset 的日志.  需要Info 级别. 如果取 Offset 出错, 会有 Error 日志.

**Comment by childe** [comment]
"gohangout 一直不消费", 应该是之前一个 Bug, Join 失败之后, 针对特定的错误需要重置memberId. https://github.com/childe/healer/issues/14

**Comment by zcola** [comment]
```
 index:g66_logtail_write index_type:_doc]
I0419 22:16:08.884179       1 filter.go:118] filter type: Convert
I0419 22:16:08.884207       1 filter.go:120] filter config: map[fields:map[batch_offset:map[to:int] batch_ts:map[to:int]]]
I0419 22:16:08.884899       1 group_consumer.go:137] coordinator for group[logstash_g66_logtail_11]:caxxxxz.i.nease.net:9092
I0419 22:16:08.884910       1 group_consumer.go:169] try to join group logstash_g66_logtail_11
I0419 22:16:11.598493       1 group_consumer.go:204] memberID now is logstash_g66_logtail_11-1587305768831-elk-doxxxnx.net-770e0361-db69-4d0e-b6a4-f43c2c2e8690
I0419 22:16:11.598602       1 group_consumer.go:216] try to sync group logstash_g66_logtail_11
I0419 22:16:11.603352       1 simple_consumer.go:88] coordinator for group[logstash_g66_logtail_11]:xxxka13-suez.i.nease.net:9092
I0419 22:16:11.603792       1 simple_consumer.go:88] coordinator for group[logstash_g66_logtail_11]:xxxa13-suez.i.nease.net:9092
I0419 22:16:11.6371
省略重复
I0419 22:16:11.719848       1 simple_consumer.go:88] coordinator for group[logstash_g66_logtail_11]:canal-xxxase.net:9092
I0419 22:16:12.830989       1 bulk_http.go:144] bulk 36000 docs with execution_id 1
I0419 22:16:12.831061       1 bulk_http.go:154] try to bulk with host (http://10.xx89:9200/_bulk)
I0419 22:16:13.817400       1 bulk_http.go:144] bulk 36000 docs with execution_id 2
```

那我是升级最新版本gohangout 就行？

**Comment by childe** [comment]
https://github.com/childe/healer/blob/b7d3d633cb3622dbb7b70244e9e25b94243e216b/simple_consumer.go#L143 
这里可以看到, 有打印日志, 说明启动时的 Offset 是多少. 

但是刚刚发现, 这里好像有问题... 不应该去leaderBroker 取 Offset, 而是应该到 Coordinator 去取的. 所以很可能取不到 Offset. 但不管有没有取到, 都应该有日志打印出来.

**Comment by zcola** [comment]
> https://github.com/childe/healer/blob/b7d3d633cb3622dbb7b70244e9e25b94243e216b/simple_consumer.go#L143
> 这里可以看到, 有打印日志, 说明启动时的 Offset 是多少.
> 
> 但是刚刚发现, 这里好像有问题... 不应该去leaderBroker 取 Offset, 而是应该到 Coordinator 去取的. 所以很可能取不到 Offset. 但不管有没有取到, 都应该有日志打印出来.

有种可能 could not get offset 打在其他实例的节点上了并开始读最新了

**Comment by zcola** [comment]
另外补充一个场景触发bug，日志是一样的，可以重现，我把topic 数据量很小，我把bulk size 调整的很大，那么应该会有一段实际空闲不去kafka 取数据还是啥，也会刷并停止消费，我把bulk size 改成默认值就没有再出现过了，没有深究，现在看来有可能是同一个问题
```
I0403 12:47:12.778799       1 group_consumer.go:190] join hangout_jinghang_lbc_zhongjing_external_faker_log error: The coordinator is not aware of this member.
I0403 12:47:12.778809       1 group_consumer.go:169] try to join group hangout_jinghang_lbc_zhongjing_external_faker_log
I0403 12:47:12.780400       1 group_consumer.go:190] join hangout_jinghang_lbc_zhongjing_external_faker_log error: The coordinator is not aware of this member.
I0403 12:47:12.780410       1 group_consumer.go:169] try to join group hangout_jinghang_lbc_zhongjing_external_faker_log
I0403 12:47:12.783710       1 group_consumer.go:190] join hangout_jinghang_lbc_zhongjing_external_faker_log error: The coordinator is not aware of this member.
I0403 12:47:12.783723       1 group_consumer.go:169] try to join group hangout_jinghang_lbc_zhongjing_external_faker_log
```

**Comment by childe** [comment]
这个想不到啥原因.  这个日志前后的也发一下吧, 看一下 Join 之前的日志, 为啥会重新 Join

**Comment by zcola** [comment]
> 这个想不到啥原因. 这个日志前后的也发一下吧, 看一下 Join 之前的日志, 为啥会重新 Join

找不到了，这个是4月3号的日志，后面把bulksize没有问题了，还是先看回第一个问题怎么解决把

**Comment by childe** [comment]
> > https://github.com/childe/healer/blob/b7d3d633cb3622dbb7b70244e9e25b94243e216b/simple_consumer.go#L143
> > 这里可以看到, 有打印日志, 说明启动时的 Offset 是多少.
> > 但是刚刚发现, 这里好像有问题... 不应该去leaderBroker 取 Offset, 而是应该到 Coordinator 去取的. 所以很可能取不到 Offset. 但不管有没有取到, 都应该有日志打印出来.
> 
> 有种可能 could not get offset 打在其他实例的节点上了并开始读最新了

打在其他实例的节点上?  没看明白.  

我之前说"好像有问题", 现在确认了, 没有问题. 太久没看代码, 自己也生疏了. 

你的两个问题.

一个是没有接着之前的 Offset 消费:
-v 5, 日志级别设置成 5 的时候, 才会打印出来启动时获取的 Offset 信息.  如果没有获取成功, 应该有错误日志. 你的没有打印错误, 又没有接着之前的 Offset 消费, 还没想到是啥原因. 

二个是没有自动恢复. 这个升级一下版本吧.  可能是 Join 的问题.

建议使用 -v 5 的日志级别.

**Comment by zcola** [comment]
这么说我开了 6个容器同时消费，那重启服务，启动总有个先后顺序吧。会不会第一个重新启动的实例重置了offset, 后面的实例就没有打印错误，这个日志只有服务器上有，不太好找。-v 5 是什么级别，日志量多不？我换最新版本gohangout 吧

**Comment by childe** [comment]
我们用的这个级别，日志不多。
应该不会有你提到的这个问题。 "重置"这个操作应该不会的。

---原始邮件---
发件人: "ZhangRui"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 晚上6:31
收件人: "childe/gohangout"<gohangout@noreply.github.com&gt;;
抄送: "childe"<rmself@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [childe/gohangout] Kafka 故障恢复后不能恢复消费，刷报错，重启后从最新开始读 (#82)




 
这么说我开了 6个容器同时消费，那重启服务，启动总有个先后顺序吧。会不会第一个重新启动的实例重置了offset, 后面的实例就没有打印错误，这个日志只有服务器上有，不太好找。-v 5 是什么级别，日志量多不？我换最新版本gohangout 吧

**Comment by zcola** [comment]
还是 1.3.1 版本，kafka 网络卡了一下，不会继续消费，但是强制重启没有丢 offset, 1.4.1 版本我已经了一部分了，准备都升上去
```
I0508 15:35:44.951821       1 bulk_http.go:161] bulk done with execution_id 58497 1.792 21171 11814.174
I0508 15:35:59.543742       1 bulk_http.go:144] bulk 30712 docs with execution_id 58498
I0508 15:35:59.546594       1 bulk_http.go:154] try to bulk with host (http://10.191.65.188:9200/_bulk)
I0508 15:36:02.347084       1 bulk_http.go:161] bulk done with execution_id 58498 2.804 30712 10952.925
E0508 15:36:40.137711       1 group_consumer.go:427] failed to send heartbeat: read tcp 10.192.0.132:42928->10.90.132.56:9092: i/o timeout
I0508 15:36:40.137754       1 broker.go:177] broker caxxxxe.net:9092 is dead, (re)open it after sleep 200ms
E0508 15:36:40.342010       1 group_consumer.go:339] commit offset logstash_g68_logtail_1203-02-1588144783132-elk-dxxxxease.net-4ef8df58-ca1f-4bc3-a834-09bd19b82d75(299) [albert_g68_logtail][162]:4138954711 error:The coordinator is not aware of this member.
E0508 15:36:40.343783       1 group_consumer.go:339] commit offset logstash_g68_logtail_1203-02-1588144783132-elk-doxxxnet-4ef8df58-ca1f-4bc3-a834-09bd19b82d75(299) [albert_g68_logtail][169]:4138956226 error:The coordinator is not aware of this member.
E0508 15:36:40.345507       1 group_consumer.go:339] commit offset logstash_g68_logtail_1203-02-1588144783132-exxxnet-4ef8df58-ca1f-4bc3-a834-09bd19b82d75(299) [albert_g68_logtail][179]:4138955530 error:The coordinator is not aware of this member.
```

**Comment by zcola** [comment]
升级到1.4.2 版本没有效果还是报，-v5 这次刚好出问题的hangout 没有配置，所以报错内容和以前一样

**Comment by childe** [comment]
15:36:40.137711 才 heartbeat 失败.  日志只截止到 15:36:40.345507 , 目前的 Error 日志都是预料中的. 如果有至少30秒之后的日志才方便看问题在哪里.

**Comment by zcola** [comment]
I0516 14:32:24.671267       1 bulk_http.go:170] 0 should retry; 11 need not retry
E0516 14:32:34.111767       1 group_consumer.go:342] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][8]:11061102295 error:read tcp 10.192.0.138:38856->10.200.46.27:9092: i/o timeout
I0516 14:32:34.111809       1 broker.go:177] broker canal-kafka06-panama:9092 is dead, (re)open it after sleep 200ms
I0516 14:32:34.426979       1 bulk_http.go:144] bulk 50 docs with execution_id 37858
I0516 14:32:34.427033       1 bulk_http.go:154] try to bulk with host (http://10.90.142.48:9200/_bulk)
I0516 14:32:34.428298       1 bulk_http.go:144] bulk 50 docs with execution_id 37841
I0516 14:32:34.428348       1 bulk_http.go:154] try to bulk with host (http://10.90.142.48:9200/_bulk)
I0516 14:32:34.429446       1 bulk_http.go:144] bulk 51 docs with execution_id 37795
I0516 14:32:34.429470       1 bulk_http.go:154] try to bulk with host (http://10.90.142.50:9200/_bulk)
I0516 14:32:34.429800       1 bulk_http.go:144] bulk 52 docs with execution_id 37824
I0516 14:32:34.429819       1 bulk_http.go:154] try to bulk with host (http://10.90.142.48:9200/_bulk)
I0516 14:32:34.801147       1 bulk_http.go:161] bulk done with execution_id 37795 0.372 51 137.097
I0516 14:32:34.801692       1 bulk_http.go:161] bulk done with execution_id 37824 0.372 52 139.785
I0516 14:32:34.802869       1 bulk_http.go:161] bulk done with execution_id 37858 0.376 50 132.979
I0516 14:32:35.732355       1 bulk_http.go:161] bulk done with execution_id 37841 1.304 50 38.344
E0516 14:32:38.449105       1 group_consumer.go:339] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][7]:11062871254 error:The coordinator is not aware of this member.
E0516 14:32:39.686851       1 group_consumer.go:339] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][16]:11061272644 error:The coordinator is not aware of this member.
E0516 14:32:39.824708       1 group_consumer.go:339] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][11]:11062666412 error:The coordinator is not aware of this member.
E0516 14:32:40.467149       1 group_consumer.go:339] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][13]:11063145122 error:The
0516 14:32:42.444132       1 group_consumer.go:339] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][9]:11062341685 error:The coordinator is not aware of this member.
E0516 14:32:42.489866       1 group_consumer.go:339] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][1]:11059824322 error:The coordinator is not aware of this member.
E0516 14:32:42.521294       1 group_consumer.go:427] failed to send heartbeat: The coordinator is not aware of this member.
E0516 14:32:42.530338       1 group_consumer.go:339] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][0]:11062135698 error:The coordinator is not aware of this member.
E0516 14:32:42.537449       1 group_consumer.go:339] commit offset hangout_panama_lbc_binan_external_haproxy_accesslog-1589427184415-elk-docker51-502-bf0467c7-8390-4af1-b7fe-87253871b5ee(1) [panama_lbc_binan_external_haproxy_accesslog][17]:11060870320 error:The coordinator is not aware of this member.

**Comment by childe** [comment]
像下面这行
`E0516 14:32:42.521294       1 group_consumer.go:427] failed to send heartbeat: The coordinator is not aware of this member.`

这个应该会触发 Rejoin, 最多30秒之后应该会有 Rejoin 的结果.

但日志到这里结束了?  后面没有更多多日志了?

**Comment by zcola** [comment]
现象就是重复刷相同报错停止消费，重启容器恢复

在 2020-05-16 18:51:53，childe <notifications@github.com> 写道：


像下面这行
E0516 14:32:42.521294 1 group_consumer.go:427] failed to send heartbeat: The coordinator is not aware of this member.

这个应该会触发 Rejoin, 最多30秒之后应该会有 Rejoin 的结果.

但日志到这里结束了? 后面没有更多多日志了?

**Comment by zcola** [comment]
使用1.4.3 几个星期，没有再出现问题

**Comment by zcola** [comment]
gohanout 1.4.3
kafka 0.10

今天遇到一个 case ，kafka 一台 broker 挂了，但是运维一直没去恢复。导致类似报错不消费2小时直到发现，强制重启时可以消费的，即时 kafka 挂了一台 broker，10.200.46.22: 就是挂掉的 broker
```
I0719 14:53:34.861110       1 broker.go:178] broker zcolase.net:9092 is dead, (re)open it after sleep 200ms
E0719 14:53:35.061882       1 broker.go:182] could not conn to zcolase.net:9092: dial tcp 10.200.46.22:9092: connect: connection refused
I0719 14:53:35.061913       1 group_consumer.go:192] join logstash_h55na_logtail error: dial tcp 10.200.46.22:9092: connect: connection refused
I0719 14:53:35.162008       1 group_consumer.go:171] try to join group logstash_h55na_logtail
I0719 14:53:35.162039       1 broker.go:178] broker zcolase.net:9092 is dead, (re)open it after sleep 200ms
E0719 14:53:35.362971       1 broker.go:182] could not conn to zcolase.net:9092: dial tcp 10.200.46.22:9092: connect: connection refused
```


重启后正常消费的日志
```
I0719 14:54:32.990490       1 filter.go:120] filter config: map[fields:map[batch_offset:map[to:int] batch_ts:map[to:int]]]
I0719 14:54:32.991808       1 group_consumer.go:139] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:32.991833       1 group_consumer.go:171] try to join group logstash_h55na_logtail
I0719 14:54:35.015919       1 group_consumer.go:209] memberID now is logstash_h55na_logtail-1595141672981-elk-docker25-5ease.net-c6fd71a1-15e0-4a98-bdf3-ab8d3432b60c
I0719 14:54:35.015961       1 group_consumer.go:221] try to sync group logstash_h55na_logtail
I0719 14:54:35.019829       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.282156       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.283337       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.284586       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.286687       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.287114       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.319510       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.320841       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.321332       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:35.322978       1 simple_consumer.go:88] coordinator for group[logstash_h55na_logtail]:zcola11se.net:9092
I0719 14:54:37.817075       1 bulk_http.go:144] bulk 32380 docs with execution_id 1
I0719 14:54:37.817143       1 bulk_http.go:154] try to bulk with host (http://10.90.140

```

**Comment by childe** [comment]
谢谢你的 Case

先确认下, 没有从头开始消费吧?

2小时前的日志, 从正常消费到开始不消费那段时间的, 发一下吧~

**Comment by childe** [comment]
看日志是 Coordinator Conn 有问题的时候, 应该重新选 Coordinator. 这个我要去改一下.

**Comment by childe** [comment]
780f4a8 处理了.

**Comment by zcola** [comment]
> 780f4a8a83acb9ced5a2a25933b4b7aade3f8057 处理了.

好的，谢谢，还需要日志吗？

**Comment by childe** [comment]
> > 780f4a8a83acb9ced5a2a25933b4b7aade3f8057 处理了.
> 
> 好的，谢谢，还需要日志吗？

先不用了~

**Comment by childe** [comment]
给 healer加了一个 Tag, 方便在 mod 里面使用.
v0.1.4

**Comment by zcola** [comment]
> 给 healer加了一个 Tag, 方便在 mod 里面使用.
> v0.1.4

那是要我自己重新编译吗，你们什么时候release 一次

**Comment by childe** [comment]
> > 给 healer加了一个 Tag, 方便在 mod 里面使用.
> > v0.1.4
> 
> 那是要我自己重新编译吗，你们什么时候release 一次

https://github.com/childe/gohangout/releases/tag/v1.4.7
