### ISSUE TITLE
clickhouse不能写入

### ISSUE THREAD

**Issue by aloasut** [childe/gohangout#83]
ClickHouse client version 19.17.4.11.
gohangout最新版

filebeat写入kafka的信息：{"serverid":101,"checkdate":"2020-03-27","checktime":"2020-03-27 21:08:34","count":54}

gohangout yml配置
`inputs:
    - Kafka:
        topic:
           online.online: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "192.168.2.247:9092"
            group.id: gohangout
outputs:
     - Clickhouse:
         table: 'online.online'
         hosts:
              - 'tcp://localhost:9000'
         fields: ['serverid','checkdate','checktime','count']
         bulkactions: 10`

clickhouse表结构：
`CREATE TABLE online.online (serverid Int64,checkdate Date,checktime DateTime,count Int64) ENGINE = MergeTree(checkdate, (serverid), 8192);`

问题：
output直接打印出来，message是能拿到日志的整段json，但是插入clickhouse以后，字段都是空的
但如果在clickhouse中使用以下语句可以插入的：
`insert into online.online ("serverid","checkdate","checktime","count") values(1040,'2020-03-27','2020-03-27 21:08:34',54);
`

**Comment by childe** [comment]
看一下stdout的内容？



---原始邮件---
发件人: "aloasut"<notifications@github.com&gt;
发送时间: 2020年4月23日(周四) 晚上8:37
收件人: "childe/gohangout"<gohangout@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [childe/gohangout] clickhouse不能写入 (#83)




 
ClickHouse client version 19.17.4.11.
 gohangout最新版
 
filebeat写入kafka的信息：{"serverid":101,"checkdate":"2020-03-27","checktime":"2020-03-27 21:08:34","count":54}
 
gohangout yml配置
 inputs: - Kafka: topic: online.online: 1 codec: json consumer_settings: bootstrap.servers: "192.168.2.247:9092" group.id: gohangout outputs: - Clickhouse: table: 'online.online' hosts: - 'tcp://localhost:9000' fields: ['serverid','checkdate','checktime','count'] bulkactions: 10
 
clickhouse表结构：
 CREATE TABLE online.online (serverid Int64,checkdate Date,checktime DateTime,count Int64) ENGINE = MergeTree(checkdate, (serverid), 8192);
 
问题：
 output直接打印出来，message是能拿到日志的整段json，但是插入clickhouse以后，字段都是空的
 但如果在clickhouse中使用以下语句可以插入的：
 insert into online.online ("serverid","checkdate","checktime","count") values(1040,'2020-03-27','2020-03-27 21:08:34',54);

**Comment by aloasut** [comment]
谢谢提示，我故意写错一个字段，在clickhouse的日志可以打印出错误的SQL语句：

`2020.04.23 20:38:54.159733 [ 45 ] {0a7401f7-a380-419a-95a8-3bda0f914129} <Error> executeQuery: Code: 16, e.displayText() = DB::Exception: No such column serverids in table online (version 19.17.4.11) (from [::1]:53124) (in query: INSERT INTO online.online ("serverids","checkdate","checktime","count") VALUES ), Stack trace:`

可以看到是VALUES为空了。

Stdout打印的内容是：
`{"@metadata":{"beat":"filebeat","topic":"online.online","type":"_doc","version":"7.0.1"},"@timestamp":"2020-04-23T11:00:50.371Z","agent":{"ephemeral_id":"dbf4303d-58d6-4415-8dc4-686c827e1d9b","hostname":"192.168.1.253","id":"88219ef6-d5f5-43dd-8ae9-4ae4d1757994","type":"filebeat","version":"7.0.1"},"ecs":{"version":"1.0.0"},"host":{"name":"192.168.1.253"},"input":{"type":"log"},"log":{"file":{"path":"/root/seaslog/log/online/online_2020032818.log"},"offset":0},"message":"{\"checktime\":\"2020-03-27 21:08:16\",\"checkdate\":\"2020-03-27\",\"count\":54,\"serverid\":1040}"}`

是我日志格式写错了吗？

**Comment by childe** [comment]
你需要的字段在message字段下面，不在第一层，用Add filter移到第一层吧。



---原始邮件---
发件人: "aloasut"<notifications@github.com&gt;
发送时间: 2020年4月23日(周四) 晚上8:46
收件人: "childe/gohangout"<gohangout@noreply.github.com&gt;;
抄送: "childe"<rmself@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [childe/gohangout] clickhouse不能写入 (#83)




 
谢谢提示，我故意写错一个字段，在clickhouse的日志可以打印出错误的SQL语句：
 
2020.04.23 20:38:54.159733 [ 45 ] {0a7401f7-a380-419a-95a8-3bda0f914129} <Error&gt; executeQuery: Code: 16, e.displayText() = DB::Exception: No such column serverids in table online (version 19.17.4.11) (from [::1]:53124) (in query: INSERT INTO online.online ("serverids","checkdate","checktime","count") VALUES ), Stack trace:
 
可以看到是VALUES为空了。
 
Stdout打印的内容是：
 {"@metadata":{"beat":"filebeat","topic":"online.online","type":"_doc","version":"7.0.1"},"@timestamp":"2020-04-23T11:00:50.371Z","agent":{"ephemeral_id":"dbf4303d-58d6-4415-8dc4-686c827e1d9b","hostname":"192.168.1.253","id":"88219ef6-d5f5-43dd-8ae9-4ae4d1757994","type":"filebeat","version":"7.0.1"},"ecs":{"version":"1.0.0"},"host":{"name":"192.168.1.253"},"input":{"type":"log"},"log":{"file":{"path":"/root/seaslog/log/online/online_2020032818.log"},"offset":0},"message":"{\"checktime\":\"2020-03-27 21:08:16\",\"checkdate\":\"2020-03-27\",\"count\":54,\"serverid\":1040}"}
 
是我日志格式写错了吗？

**Comment by aloasut** [comment]
> 你需要的字段在message字段下面，不在第一层，用Add filter移到第一层吧。
> […](#)
> ---原始邮件--- 发件人: "aloasut"<notifications@github.com&gt; 发送时间: 2020年4月23日(周四) 晚上8:46 收件人: "childe/gohangout"<gohangout@noreply.github.com&gt;; 抄送: "childe"<rmself@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [childe/gohangout] clickhouse不能写入 (#83) 谢谢提示，我故意写错一个字段，在clickhouse的日志可以打印出错误的SQL语句： 2020.04.23 20:38:54.159733 [ 45 ] {0a7401f7-a380-419a-95a8-3bda0f914129} <Error&gt; executeQuery: Code: 16, e.displayText() = DB::Exception: No such column serverids in table online (version 19.17.4.11) (from [::1]:53124) (in query: INSERT INTO online.online ("serverids","checkdate","checktime","count") VALUES ), Stack trace: 可以看到是VALUES为空了。 Stdout打印的内容是： {"@metadata":{"beat":"filebeat","topic":"online.online","type":"_doc","version":"7.0.1"},"@timestamp":"2020-04-23T11:00:50.371Z","agent":{"ephemeral_id":"dbf4303d-58d6-4415-8dc4-686c827e1d9b","hostname":"192.168.1.253","id":"88219ef6-d5f5-43dd-8ae9-4ae4d1757994","type":"filebeat","version":"7.0.1"},"ecs":{"version":"1.0.0"},"host":{"name":"192.168.1.253"},"input":{"type":"log"},"log":{"file":{"path":"/root/seaslog/log/online/online_2020032818.log"},"offset":0},"message":"{\"checktime\":\"2020-03-27 21:08:16\",\"checkdate\":\"2020-03-27\",\"count\":54,\"serverid\":1040}"} 是我日志格式写错了吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问应该如何移动？我下面这样试了也不行：

inputs:
    - Kafka:
        topic:
            online.online: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "192.168.2.247:9092"
            group.id: gohangout
Add:
    overwrite: true
    fields:
        serverid: '[message][serverid]'
        checkdate: '[message][checkdate]'
        checktime: '[message][checktime]'
        count: '[message][count]'
outputs:
     - Stdout: {}
     - Clickhouse:
         table: 'online.online'
         hosts:
              - 'tcp://localhost:9000'
         fields: ['serverixd','checkdate','checktime','count']
         bulkactions: 10

**Comment by childe** [comment]
抱歉, 是我没看清. message 字段是一个字符串, 需要 Json 解析一下, 配置如下.  直接用就行了, 不用 Add 了.

```yaml
inputs:
  - Stdin:
      codec: json
filters:
  - Json:
      field: message

outputs:
  - Stdout: {}
```

**Comment by aloasut** [comment]
谢谢，最后还是没搞定，用Json也无法拿到值。最后日志用分隔符搞定了。

serverid:1043|checkdate:2020-03-27|checktime:2020-03-27 21:08:34|count:54

inputs:
    - Kafka:
        topic:
            online.online: 1
        codec: json
        consumer_settings:
            bootstrap.servers: "192.168.2.247:9092"
            group.id: gohangout
filters:
    - KV:
        src: message
        field_split: '|'
        value_split: ':'
        trim: '\t "'
        trimkey: '"'
        tag_on_failure: "KVfail"
        remove_fields: ['message']
    - Convert:
        fields:
           serverid:
                to: int
           count:
                to: int
outputs:
     - Stdout: {}
     - Clickhouse:
         table: 'online.online'
         hosts:
              - 'tcp://localhost:9000'
         fields: [serverid,checkdate,checktime,count]
         bulkactions: 10
         flush_interval: 1
