### ISSUE TITLE
不支持 to:string

### ISSUE THREAD

**Issue by listr0ng** [childe/gohangout#88]
您好 readme 教程显示支持to: string 但实际测试会报错 can only convert to int/float/bool

**Comment by childe** [comment]
客气~

https://github.com/childe/gohangout/pull/73 支持 String 是这个PR 里面写的, 但是就像我在 PR 里面写的, 只能 reset 了.  应该是这个过程出问题了, 我去处理下.

**Comment by childe** [comment]
fix 473399a6fca465ff562c7b32e903d3596d24c55f
