### ISSUE TITLE
Clickhouse driver: bad connection

### ISSUE THREAD

**Issue by childe** [childe/gohangout#95]
在运行过程中，偶尔会出现
clickhouse_output.go:318] transaction prepare statement error: driver: bad connection
这个错误

**Comment by childe** [comment]
报错是因为 Clickhouse 的 Conn 因为某些原因不可用了, 比如说因为 Idle 时间太长被防火墙丢弃了.
一个解决的方法是给 Conn 设置 LiveTime, 这样可以 在 Conn不能用之前主动放弃这个 Conn.

**Comment by childe** [comment]
#12e8c72cf45e8765ab72ff1cea9c65a0356d128c

**Comment by fvn4edal** [comment]
作者您好，使用clickhouse conn_max_life_time设置成1分钟，还是偶尔会出现丢失数据的情况。即数据没有从kafka写入clickhouse。我发现丢失数据的时候一般都会有bad connection,但是不是每次出现bad connection日志都会报错。不知道具体原因是什么。

**Comment by childe** [comment]
你是哪个版本?  是怎么配置的?

**Comment by childe** [comment]
我又大概看了下 Clickhouse 的代码, 好像这里他没有把 Closed Conn 丢掉再取新的 Conn.
我建议把 conn_max_life_time 设置长一点. (配合 Linux 系统下设置 Tcp keepalive时间)

但我也没有确认, 还要仔细看一下代码. 我也自己再测一下看.

**Comment by fvn4edal** [comment]
> 我又大概看了下 Clickhouse 的代码, 好像这里他没有把 Closed Conn 丢掉再取新的 Conn.
> 我建议把 conn_max_life_time 设置长一点. (配合 Linux 系统下设置 Tcp keepalive时间)
> 
> 但我也没有确认, 还要仔细看一下代码. 我也自己再测一下看.

您好，我的版本是a3ea5e2bebb471408e71edee129a1616a9aeeaa3
就是我同事提交的：update clickhouse output #91
我们发现有一些kafka topic数据更新频率很低，所以会有丢数据的情况，后面我们就把livetime调到分钟级别了。开始以为解决了这个问题，后面发现其实还是有丢数据的情况，但也不是每次都丢。很诡异。所以我就想问问作者你有什么解决办法没有。根据我们的测试，好像livetime设置时间越长，反而越容易丢数据。

**Comment by kingwide** [comment]
发现实时写入的数据没有问题，十分钟一批写入kafka的数据就会报Clickhouse driver: bad connection 这个错，丢数据很多 
![image](https://user-images.githubusercontent.com/48897677/124587904-c3fe2d00-de8a-11eb-925e-6a2949ad180d.png)

conn_max_life_time: 60
bulk_actions: 100000
        flush_interval: 10
        ncurrent: 2
请问参数有可调整的地方吗

**Comment by kingwide** [comment]
发现实时写入的数据没有问题，十分钟一批写入kafka的数据就会报Clickhouse driver: bad connection 这个错，丢数据很多 
![image](https://user-images.githubusercontent.com/48897677/124587904-c3fe2d00-de8a-11eb-925e-6a2949ad180d.png)

conn_max_life_time: 60
bulk_actions: 100000
        flush_interval: 10
        ncurrent: 2
请问参数有可调整的地方吗

**Comment by kingwide** [comment]
发现实时写入的数据没有问题，十分钟一批写入kafka的数据就会报Clickhouse driver: bad connection 这个错，丢数据很多 
![image](https://user-images.githubusercontent.com/48897677/124587904-c3fe2d00-de8a-11eb-925e-6a2949ad180d.png)

conn_max_life_time: 60
bulk_actions: 100000
        flush_interval: 10
        ncurrent: 2
请问参数有可调整的地方吗

**Comment by childe** [comment]
@kingwide  clickhouse 配置里面加一个 debug 看一下吧。类似下面这样 

```
conn_max_life_time: 60
debug: true
```

**Comment by childe** [comment]
@kingwide 我这边测了是正常的，隔了一天再写新消息也正常写入了。 开了 Debug 之后的一些 Debug 信息如下：

```
[clickhouse]host(s)=127.0.0.1:9000, database=docker, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=3, server=0 -> 127.0.0.1:9000
[clickhouse][connect=3][hello] -> Golang SQLDriver 1.1.54213
[clickhouse][connect=3][hello] <- ClickHouse 21.3.54447 (UTC)
[clickhouse][connect=3][begin] tx=false, data=false
[clickhouse][connect=3][prepare] INSERT INTO docker.docker ("x") VALUES (?)
[clickhouse][connect=3][send query] INSERT INTO docker.docker ("x") VALUES
[clickhouse][connect=3][read meta] <- data: packet=1, columns=1, rows=0
[clickhouse][connect=3][commit] tx=true, data=true
[clickhouse][connect=3][process] <- end of stream
[clickhouse][connect=3][stmt] close
```
